























const P = (t) => ({ s: "PIL", t });
const A = (t) => ({ s: "ATC", t });

export const CATEGORIES = [
  {
    id: "general",
    title: "General Procedures",
    icon: "compass",
    topics: [
      {
        id: "radio-check",
        title: "Radio Check",
        when: "Checks that your transmitter and receiver work before you rely on them, usually on the ground before start-up or on first contact with a new station. You state the frequency so the station can confirm you are tuned correctly.",
        pilot: "[Station] [Callsign] RADIO CHECK [frequency]",
        atc: "[Callsign] [Station] READABILITY [1–5]",
        convo: [P("Delhi Ground, WEONE 214, radio check 121.75"), A("WEONE 214, Delhi Ground, readability 5"), P("Readability 5, WEONE 214")],
        notes: [
          "Readability scale: 1 unreadable, 2 readable now and then, 3 readable but with difficulty, 4 readable, 5 perfectly readable.",
          "Keep the check short. A radio check is not a chance to pass other requests.",
          "If you are told readability 3 or worse, check volume and squelch, then try the next frequency.",
        ],
        ref: "ICAO Doc 9432: test procedures",
      },
      {
        id: "how-do-you-read",
        title: "How Do You Read",
        when: "Used once contact is already established, when you suspect the signal has degraded, for example after a missed call or a broken reply. No frequency is stated because the station already knows which channel you are on.",
        pilot: "[Station] [Callsign] HOW DO YOU READ",
        atc: "[Callsign] READ YOU [1–5]",
        convo: [P("Mumbai Control, WEONE 214, how do you read"), A("WEONE 214, read you 4"), P("Read you 5, WEONE 214")],
        notes: ["ATC may add a remark, for example \"read you 3, transmission broken\".", "Answer with your own readability of the station so both sides know the link quality."],
        ref: "ICAO Doc 9432: test procedures",
      },
      {
        id: "time-check",
        title: "Request Time Check",
        when: "Used to synchronise the aircraft clock with ATC before departure or before a timed procedure. Time is given in UTC to the nearest minute, and to the nearest half minute when accuracy matters.",
        pilot: "[Station] [Callsign] REQUEST TIME CHECK",
        atc: "[Callsign] TIME [hh mm]",
        convo: [P("Chennai Ground, WEONE 214, request time check"), A("WEONE 214, time 0935"), P("0935, WEONE 214")],
        notes: ["Minutes alone are normally enough (\"time three five\"); give the hour too when there is any doubt.", "Every digit is spoken separately: 0935 is \"zero niner tree fife\"."],
        ref: "ICAO Doc 9432: transmission of time",
      },
      {
        id: "say-again",
        title: "Say Again",
        when: "Asks for all or part of the last transmission to be repeated. Never use \"repeat\" for this; in RT that word is avoided because of its military meaning.",
        pilot: "[Callsign] SAY AGAIN [ALL AFTER / ALL BEFORE / WORD BEFORE ... ]",
        atc: "[Callsign] I SAY AGAIN [message]",
        convo: [A("WEONE 214, turn right heading 140, climb FL150"), P("WEONE 214, say again all after heading"), A("WEONE 214, I say again, climb FL150"), P("Climb FL150, WEONE 214")],
        notes: ["Narrow the request: \"say again all after\", \"all before\", \"word after\", \"word before\".", "The reply starts with \"I say again\" so everyone knows it is a repetition."],
        ref: "ICAO Doc 9432: standard words and phrases",
      },
      {
        id: "words-twice",
        title: "Words Twice",
        when: "Used when communication is difficult (static, interference, weak signal). As a request it asks the station to send every word or group twice; as information it tells them you will do so.",
        pilot: "[Station] [Callsign] WORDS TWICE",
        atc: "[Callsign] [message sent with each word or group twice]",
        convo: [P("Kolkata Control, WEONE 214, words twice"), A("WEONE 214 WEONE 214, climb climb FL310 FL310"), P("Climb climb FL310 FL310, WEONE 214 WEONE 214")],
        notes: ["Only use it when reception is genuinely poor; it doubles channel occupancy.", "Cancel it when conditions improve by simply returning to normal transmissions."],
        ref: "ICAO Doc 9432: standard words and phrases",
      },
      {
        id: "readback",
        title: "Readback of Clearances",
        when: "Safety-related parts of a clearance must be read back so ATC can catch errors: ATC route clearances, runway clearances (enter, land, take off, cross, hold short, backtrack), runway in use, altimeter settings, SSR codes, level, heading and speed instructions, and transition levels.",
        pilot: "[Safety-critical items read back] [Callsign]",
        atc: "[Callsign] READBACK CORRECT (or the correction)",
        convo: [A("WEONE 214, descend FL120, QNH 1008, squawk 4521"), P("Descend FL120, QNH 1008, squawk 4521, WEONE 214")],
        notes: ["End the readback with your callsign.", "\"Roger\" or \"wilco\" alone is never an acceptable readback of these items.", "If ATC hears an error they say \"negative, I say again\" followed by the correct item."],
        ref: "ICAO Doc 9432: readback requirements; Annex 11",
      },
      {
        id: "unable",
        title: "Unable to Comply",
        when: "Used when you cannot accept an instruction, clearance or request, for example because of performance, weather or fuel. State the reason when you can, and offer an alternative.",
        pilot: "[Station] [Callsign] UNABLE [instruction] DUE [reason]",
        atc: "[Callsign] [alternative instruction]",
        convo: [A("WEONE 214, climb FL390"), P("WEONE 214, unable FL390 due weight, request FL350"), A("WEONE 214, roger, climb FL350"), P("Climb FL350, WEONE 214")],
        notes: ["\"Unable\" is the standard word; do not say \"negative\" to decline a clearance.", "Say it early. ATC needs time to plan an alternative."],
        ref: "ICAO Doc 9432: standard words and phrases",
      },
      {
        id: "all-stations",
        title: "Broadcast to All Stations",
        when: "A general call to every station on frequency when you need nobody in particular to answer, such as an ATC notice of a frequency change or an unlit runway.",
        pilot: "ALL STATIONS [Station] [message]",
        atc: "(No reply is expected)",
        convo: [A("All stations, Hyderabad Tower, runway 27 closed for inspection until 0830, expect runway 09")],
        notes: ["No station acknowledges an \"all stations\" call unless asked to.", "Pilots rarely originate it; one exception is a blind broadcast when uncontrolled."],
        ref: "ICAO Doc 9432: general call",
      },
      {
        id: "standby",
        title: "Standby",
        when: "\"Wait and I will call you.\" Used when you have heard the call but are too busy to answer yet. It is not an approval or a refusal.",
        pilot: "[Callsign] STANDBY",
        atc: "[Callsign] STANDBY",
        convo: [A("WEONE 214, report your estimate for PENAK"), P("WEONE 214, standby"), P("Chennai Control, WEONE 214, estimating PENAK at 0712")],
        notes: ["After \"standby\" the caller must come back to you; you must come back with the answer.", "Do not follow \"standby\" with the request that caused it: ATC is handling other traffic."],
        ref: "ICAO Doc 9432: standard words and phrases",
      },
      {
        id: "affirm-negative",
        title: "Affirm, Negative, Roger, Wilco",
        when: "The four short replies that confirm or decline. Each has one exact meaning, and mixing them up is a common exam error.",
        pilot: "AFFIRM / NEGATIVE / ROGER / WILCO [Callsign]",
        atc: "(as required)",
        convo: [A("WEONE 214, confirm you are descending FL120"), P("Affirm, WEONE 214"), A("WEONE 214, report passing FL150"), P("Wilco, WEONE 214")],
        notes: [
          "AFFIRM: yes. NEGATIVE: no, not correct, or permission not granted.",
          "ROGER: I have received all of your last transmission. It never answers a question needing yes or no.",
          "WILCO: I understand your message and will comply with it. Do not say \"roger wilco\".",
        ],
        ref: "ICAO Doc 9432: standard words and phrases",
      },
      {
        id: "numbers",
        title: "Transmission of Numbers",
        when: "Numbers are sent digit by digit, except whole hundreds and thousands in altitudes, cloud heights, visibility and RVR, which use \"hundred\" and \"thousand\".",
        pilot: "[digits] / [thousands] THOUSAND [hundreds] HUNDRED",
        atc: "(as required)",
        convo: [A("WEONE 214, climb FL180, turn left heading 300, contact Departure 124.3"), P("Climb FL180, left heading 300, Departure 124.3, WEONE 214")],
        notes: [
          "Say 3 as \"tree\", 4 as \"fower\", 5 as \"fife\", 9 as \"niner\" and thousand as \"tousand\".",
          "Flight levels, headings, squawks, frequencies and QNH are always digit by digit.",
          "The decimal point in a frequency is \"decimal\".",
        ],
        ref: "ICAO Annex 10 Vol II; ICAO Doc 9432: transmission of numbers",
      },
    ],
  },
  {
    id: "ground",
    title: "Pre-Departure & Ground",
    icon: "gear",
    topics: [
      {
        id: "request-atis",
        title: "Request ATIS",
        when: "When the automated ATIS broadcast cannot be received, you ask the ground station for the current information. Normally you listen to ATIS yourself and quote its letter on first contact.",
        pilot: "[Station] [Callsign] REQUEST INFORMATION",
        atc: "[Callsign] INFORMATION [letter] CURRENT, [key elements]",
        convo: [P("Hyderabad Ground, WEONE 214, stand 12, unable to receive ATIS, request information"), A("WEONE 214, information Charlie current, runway 27, wind 270 degrees 10 knots, QNH 1009"), P("Runway 27, QNH 1009, WEONE 214")],
        notes: ["Read back runway in use and QNH.", "Once you have received the ATIS, quote its letter on every first call: \"information Charlie\"."],
        ref: "ICAO Doc 9432: aerodrome control",
      },
      {
        id: "departure-clearance",
        title: "Departure Clearance (IFR)",
        when: "Requested from Clearance Delivery or Ground before start-up. The clearance gives clearance limit, route or SID, initial level, squawk and departure frequency, and every element must be read back.",
        pilot: "[Station] [Callsign] [stand] REQUEST CLEARANCE [destination] [information letter]",
        atc: "[Callsign] CLEARED [limit] [route/SID] CLIMB [level] SQUAWK [code] [departure frequency]",
        convo: [
          P("Hyderabad Ground, WEONE 214, stand 12, IFR to Chennai, information Charlie, request clearance"),
          A("WEONE 214, cleared to Chennai, KARNO 1A departure, flight planned route, climb FL80, squawk 5231, departure frequency 124.3"),
          P("Cleared to Chennai, KARNO 1A departure, flight planned route, climb FL80, squawk 5231, departure 124.3, WEONE 214"),
          A("WEONE 214, readback correct"),
        ],
        notes: ["A common memory aid for the order is C-R-A-F-T: Clearance limit, Route, Altitude, Frequency, Transponder.", "Write the clearance down before reading it back."],
        ref: "ICAO Doc 9432: ATC route clearances",
      },
      {
        id: "startup",
        title: "Start-Up",
        when: "Requested when ready to start engines, where the aerodrome requires start-up approval. State stand, ATIS letter and, where required, the temperature-dependent start-up request.",
        pilot: "[Station] [Callsign] [stand] REQUEST START-UP [information letter]",
        atc: "[Callsign] START-UP APPROVED / EXPECT START-UP AT [time]",
        convo: [P("Hyderabad Ground, WEONE 214, stand 12, request start-up, information Charlie"), A("WEONE 214, start-up approved, QNH 1009"), P("Start-up approved, QNH 1009, WEONE 214")],
        notes: ["If there is a delay ATC gives an expected time, for example \"expect start-up at 0625\"."],
        ref: "ICAO Doc 9432: start-up procedures",
      },
      {
        id: "pushback",
        title: "Pushback",
        when: "At stands where the aircraft must be pushed back by a tug, you request approval before the push begins. ATC may give a direction to face.",
        pilot: "[Station] [Callsign] [stand] REQUEST PUSHBACK",
        atc: "[Callsign] PUSHBACK APPROVED [facing ...]",
        convo: [P("Mumbai Ground, WEONE 318, stand 42, request pushback"), A("WEONE 318, pushback approved, face west"), P("Pushback approved, face west, WEONE 318")],
        notes: ["Pushback and start-up may be combined: \"request pushback and start-up\"."],
        ref: "ICAO Doc 9432: pushback",
      },
      {
        id: "taxi",
        title: "Request Taxi",
        when: "Requested when ready to move under your own power. ATC gives the route and holding point; read back the holding point, any runway crossings and any hold-short instructions.",
        pilot: "[Station] [Callsign] [position] REQUEST TAXI",
        atc: "[Callsign] TAXI TO HOLDING POINT [runway] VIA [taxiways] [QNH]",
        convo: [P("Hyderabad Ground, WEONE 214, stand 12, request taxi"), A("WEONE 214, taxi to holding point runway 27 via Alpha and Charlie, QNH 1009"), P("Taxi holding point runway 27 via Alpha and Charlie, QNH 1009, WEONE 214")],
        notes: ["A taxi clearance to a holding point is not a clearance to enter or cross any runway on the way.", "If unsure of the route, ask: \"request detailed taxi instructions\"."],
        ref: "ICAO Doc 9432: taxi instructions",
      },
      {
        id: "cross-runway",
        title: "Crossing a Runway",
        when: "Any crossing of an active runway needs an explicit clearance, and you report when you are clear. Hold-short instructions must be read back.",
        pilot: "[Callsign] REQUEST CROSS RUNWAY [designator]",
        atc: "[Callsign] CROSS RUNWAY [designator] REPORT VACATED / HOLD SHORT RUNWAY [designator]",
        convo: [A("WEONE 214, hold short runway 09L"), P("Holding short runway 09L, WEONE 214"), A("WEONE 214, cross runway 09L, report vacated"), P("Crossing runway 09L, WEONE 214"), P("WEONE 214, runway 09L vacated")],
        notes: ["Report \"runway vacated\" only when the whole aircraft is past the holding position on the far side."],
        ref: "ICAO Doc 9432: runway crossing",
      },
      {
        id: "ready-departure",
        title: "Ready for Departure",
        when: "Reported at the holding point when you are ready to line up. The words \"take off\" are kept for the take-off clearance itself, so the pilot says \"ready for departure\".",
        pilot: "[Station] [Callsign] READY FOR DEPARTURE [runway]",
        atc: "[Callsign] LINE UP AND WAIT / CLEARED FOR TAKE-OFF",
        convo: [P("Hyderabad Tower, WEONE 214, holding point runway 27, ready for departure"), A("WEONE 214, line up and wait runway 27"), P("Line up and wait runway 27, WEONE 214")],
        notes: ["Never say \"ready for take-off\"; it risks being mistaken for a clearance.", "Line up and wait means enter the runway and stop; it is not a take-off clearance."],
        ref: "ICAO Doc 9432: departure phraseology",
      },
      {
        id: "technical-return",
        title: "Technical Problem During Taxi",
        when: "If a fault appears while taxiing, tell ATC what you need: to stop, to return to stand, or to hold for troubleshooting.",
        pilot: "[Station] [Callsign] [problem] REQUEST [return to stand / hold position]",
        atc: "[Callsign] [instructions]",
        convo: [P("Hyderabad Ground, WEONE 214, hydraulic caution, request return to stand"), A("WEONE 214, taxi to stand 12 via Charlie and Alpha"), P("Taxi stand 12 via Charlie and Alpha, WEONE 214")],
        notes: ["Stop first if in doubt: \"WEONE 214, stopping\"."],
        ref: "ICAO Doc 9432: aerodrome control",
      },
    ],
  },
  {
    id: "departure",
    title: "Departure",
    icon: "takeoff",
    topics: [
      {
        id: "takeoff-clearance",
        title: "Take-Off Clearance",
        when: "The only time the words \"cleared for take-off\" are used. The clearance includes the runway and usually the surface wind; read back the runway.",
        pilot: "CLEARED FOR TAKE-OFF [runway] [Callsign]",
        atc: "[Callsign] [wind] RUNWAY [designator] CLEARED FOR TAKE-OFF",
        convo: [A("WEONE 214, wind 270 degrees 10 knots, runway 27, cleared for take-off"), P("Cleared for take-off runway 27, WEONE 214")],
        notes: ["If you are not ready when cleared, say \"unable\" rather than delay on the runway."],
        ref: "ICAO Doc 9432: take-off clearance",
      },
      {
        id: "stop-takeoff",
        title: "Stopping / Cancelled Take-Off",
        when: "ATC may cancel a take-off clearance; a pilot who rejects a take-off tells ATC as soon as workload allows.",
        pilot: "[Callsign] STOPPING",
        atc: "[Callsign] STOP IMMEDIATELY [repeat callsign] STOP IMMEDIATELY",
        convo: [A("WEONE 214, stop immediately, WEONE 214, stop immediately"), P("Stopping, WEONE 214")],
        notes: ["If you have not started the roll: ATC says \"hold position, cancel take-off, I say again cancel take-off\"; reply \"holding, WEONE 214\"."],
        ref: "ICAO Doc 9432: take-off clearance",
      },
      {
        id: "contact-departure",
        title: "Contact Departure",
        when: "Once airborne, Tower transfers you to Departure or Approach. On first contact give callsign, SID if any, passing level and cleared level.",
        pilot: "[Station] [Callsign] [SID] PASSING [level] CLIMBING [level]",
        atc: "[Callsign] IDENTIFIED [instructions]",
        convo: [A("WEONE 214, contact Departure 124.3"), P("124.3, WEONE 214"), P("Hyderabad Departure, WEONE 214, KARNO 1A, passing 2500 feet climbing FL80"), A("WEONE 214, identified, climb FL150"), P("Climb FL150, WEONE 214")],
        notes: ["\"Contact\" means establish contact on the new frequency; \"monitor\" means listen only."],
        ref: "ICAO Doc 9432: transfer of communication",
      },
      {
        id: "level-restriction",
        title: "Climb with Restriction",
        when: "ATC may clear you to climb with a restriction at a point or level, for example to cross traffic or airspace.",
        pilot: "[clearance with restriction] [Callsign]",
        atc: "[Callsign] CLIMB [level] TO BE LEVEL [point/time]",
        convo: [A("WEONE 214, climb FL240, to be level by TELIM"), P("Climb FL240, level by TELIM, WEONE 214")],
        notes: ["Read back the restriction as well as the level.", "If you cannot meet it, say \"unable\" at once."],
        ref: "ICAO Doc 9432: level instructions",
      },
      {
        id: "report-passing",
        title: "Report Passing a Level",
        when: "ATC asks for a report passing a level to keep separation with other traffic.",
        pilot: "[Callsign] PASSING [level]",
        atc: "[Callsign] REPORT PASSING [level]",
        convo: [A("WEONE 214, report passing FL100"), P("Wilco, WEONE 214"), P("WEONE 214, passing FL100")],
        notes: ["Make the report as you pass, not after."],
        ref: "ICAO Doc 9432: level instructions",
      },
    ],
  },
  {
    id: "enroute",
    title: "En Route",
    icon: "map",
    topics: [
      {
        id: "position-report",
        title: "Position Report",
        when: "Required at compulsory reporting points outside radar coverage, or when ATC asks. The standard order is callsign, position, time, level, next position and ETA, then the following point.",
        pilot: "[Station] [Callsign] [position] [time] [level] [next position] [ETA] [following point]",
        atc: "[Callsign] ROGER [instructions]",
        convo: [P("Chennai Control, WEONE 214, RUDRA 0655, FL330, estimating PENAK 0706, SAVRI next"), A("WEONE 214, roger")],
        notes: ["Once radar-identified, ATC may say \"omit position reports\"."],
        ref: "ICAO Doc 9432: position reporting",
      },
      {
        id: "request-level",
        title: "Request Level Change",
        when: "Ask for a new level for weather, turbulence or better economy. Give the reason when it helps ATC.",
        pilot: "[Station] [Callsign] REQUEST [climb/descent] [level] [reason]",
        atc: "[Callsign] CLIMB/DESCEND [level] / EXPECT [level] AT [point]",
        convo: [P("Chennai Control, WEONE 214, request climb FL350"), A("WEONE 214, unable due traffic, expect FL350 at PENAK"), P("Expect FL350 at PENAK, WEONE 214")],
        notes: ["An \"expect\" is not a clearance. Stay at your level until cleared."],
        ref: "ICAO Doc 9432: area control",
      },
      {
        id: "direct-to",
        title: "Request Direct Routing",
        when: "Ask to fly directly to a later point on the route to save time or fuel.",
        pilot: "[Station] [Callsign] REQUEST DIRECT [point]",
        atc: "[Callsign] PROCEED DIRECT [point]",
        convo: [P("Chennai Control, WEONE 214, request direct SAVRI"), A("WEONE 214, proceed direct SAVRI"), P("Direct SAVRI, WEONE 214")],
        notes: [],
        ref: "ICAO Doc 9432: area control",
      },
      {
        id: "weather-deviation",
        title: "Weather Deviation",
        when: "Ask to deviate from track around thunderstorms or turbulence, giving direction and distance.",
        pilot: "[Station] [Callsign] REQUEST DEVIATION [left/right] [distance] DUE WEATHER",
        atc: "[Callsign] DEVIATION [left/right] APPROVED, REPORT BACK ON TRACK",
        convo: [P("Chennai Control, WEONE 214, request deviation 15 miles right of track due weather"), A("WEONE 214, deviation up to 15 miles right approved, report back on track"), P("Up to 15 miles right approved, wilco, WEONE 214"), P("WEONE 214, back on track")],
        notes: ["If you must deviate before approval, act and tell ATC immediately."],
        ref: "ICAO Doc 9432: area control",
      },
      {
        id: "transfer-control",
        title: "Transfer Between Sectors",
        when: "When leaving one sector you are told to contact the next. On first contact give callsign and level (and any climb or descent in progress).",
        pilot: "[frequency] [Callsign] ... [Station] [Callsign] [level]",
        atc: "[Callsign] CONTACT [Station] [frequency]",
        convo: [A("WEONE 214, contact Chennai Control 132.7"), P("132.7, WEONE 214"), P("Chennai Control, WEONE 214, FL330"), A("WEONE 214, Chennai Control, identified")],
        notes: ["Read back the frequency."],
        ref: "ICAO Doc 9432: transfer of communication",
      },
    ],
  },
  {
    id: "arrival",
    title: "Arrival & Approach",
    icon: "landing",
    topics: [
      {
        id: "descent",
        title: "Descent Clearance",
        when: "Descent clearances give the new level and often an altimeter setting. Below the transition level you report altitude on QNH.",
        pilot: "DESCEND [level] [QNH] [Callsign]",
        atc: "[Callsign] DESCEND [level/altitude] [QNH]",
        convo: [A("WEONE 214, descend to altitude 4000 feet, QNH 1010"), P("Descend altitude 4000 feet, QNH 1010, WEONE 214")],
        notes: ["Say \"altitude\" before feet on QNH and \"flight level\" on standard pressure, so there is no doubt which datum you mean."],
        ref: "ICAO Doc 9432: approach control",
      },
      {
        id: "ils-approach",
        title: "ILS Approach",
        when: "ATC gives vectors to the final approach course and then clears the approach. Report established when on the localizer.",
        pilot: "[Callsign] ESTABLISHED LOCALIZER [runway]",
        atc: "[Callsign] CLEARED ILS APPROACH RUNWAY [designator]",
        convo: [A("WEONE 214, turn left heading 100, cleared ILS approach runway 07, report established"), P("Left heading 100, cleared ILS approach runway 07, wilco, WEONE 214"), P("WEONE 214, established localizer runway 07")],
        notes: ["Read back the approach type and runway."],
        ref: "ICAO Doc 9432: approach control",
      },
      {
        id: "holding",
        title: "Holding",
        when: "ATC may hold you at a fix when there is a delay. The clearance includes the fix, level, and an expected approach or onward clearance time.",
        pilot: "[holding clearance read back] [Callsign]",
        atc: "[Callsign] HOLD AT [fix] [level] EXPECT APPROACH [time]",
        convo: [A("WEONE 214, hold at SAVRI FL120, expect approach 0735"), P("Hold at SAVRI FL120, expect approach 0735, WEONE 214")],
        notes: ["If the published hold is not used, ATC adds inbound track, turn direction and leg time."],
        ref: "ICAO Doc 9432: holding",
      },
      {
        id: "landing-clearance",
        title: "Landing Clearance",
        when: "Given by Tower on final. Read back the runway. \"Cleared to land\" is the only acceptable permission to land.",
        pilot: "CLEARED TO LAND [runway] [Callsign]",
        atc: "[Callsign] [wind] RUNWAY [designator] CLEARED TO LAND",
        convo: [P("Chennai Tower, WEONE 214, final runway 07"), A("WEONE 214, wind 090 degrees 8 knots, runway 07, cleared to land"), P("Cleared to land runway 07, WEONE 214")],
        notes: [],
        ref: "ICAO Doc 9432: final approach and landing",
      },
      {
        id: "go-around",
        title: "Go-Around",
        when: "A missed approach initiated by ATC or by the pilot. Fly it first, then tell ATC. The pilot phrase is \"going around\".",
        pilot: "[Callsign] GOING AROUND",
        atc: "[Callsign] GO AROUND [instructions]",
        convo: [P("WEONE 214, going around"), A("WEONE 214, roger, climb 3000 feet, fly runway heading"), P("Climb 3000 feet, runway heading, WEONE 214")],
        notes: ["Aviate first: the call waits until the aircraft is climbing safely."],
        ref: "ICAO Doc 9432: missed approach",
      },
      {
        id: "vacated",
        title: "Runway Vacated",
        when: "After landing, report when the aircraft is clear of the runway if asked, then taxi on Ground frequency.",
        pilot: "[Callsign] RUNWAY VACATED",
        atc: "[Callsign] CONTACT GROUND [frequency]",
        convo: [A("WEONE 214, vacate left via Echo, report runway vacated"), P("Left via Echo, wilco, WEONE 214"), P("WEONE 214, runway vacated"), A("WEONE 214, contact Ground 121.9"), P("121.9, WEONE 214")],
        notes: [],
        ref: "ICAO Doc 9432: after landing",
      },
    ],
  },
  {
    id: "met",
    title: "Meteorological",
    icon: "cloud",
    topics: [
      {
        id: "wind",
        title: "Surface Wind",
        when: "Wind direction is in degrees magnetic for take-off and landing (degrees true in METARs), speed in knots. Gusts and variations follow.",
        pilot: "(read as given)",
        atc: "WIND [ddd] DEGREES [ss] KNOTS [GUSTING gg KNOTS]",
        convo: [A("WEONE 318, wind 240 degrees 15 knots gusting 25 knots, runway 27, cleared to land"), P("Cleared to land runway 27, WEONE 318")],
        notes: ["Every digit is separate: 240 is \"two fower zero\".", "Calm wind is reported as \"wind calm\"."],
        ref: "ICAO Doc 9432: transmission of meteorological information",
      },
      {
        id: "visibility-rvr",
        title: "Visibility and RVR",
        when: "Visibility below 5 km is given in metres and from 5 km in kilometres; 10 km or more is \"visibility one zero kilometres\". RVR is given per runway, and per zone when there are several readings.",
        pilot: "(read as given)",
        atc: "VISIBILITY [value] / RVR RUNWAY [designator] [value] METRES",
        convo: [A("WEONE 318, RVR runway 27, 550 metres"), P("RVR 550 metres, WEONE 318")],
        notes: ["Values in whole thousands and hundreds use \"thousand\" and \"hundred\": 1500 m is \"one tousand fife hundred metres\"."],
        ref: "ICAO Doc 9432: transmission of meteorological information",
      },
      {
        id: "cloud",
        title: "Cloud",
        when: "Cloud is described by amount (few, scattered, broken, overcast) and height of base in feet, with type only for CB and TCU.",
        pilot: "(read as given)",
        atc: "[FEW/SCATTERED/BROKEN/OVERCAST] [height] FEET [CB/TCU]",
        convo: [A("WEONE 214, information Charlie, cloud broken 1500 feet")],
        notes: ["FEW 1–2 oktas, SCATTERED 3–4, BROKEN 5–7, OVERCAST 8."],
        ref: "ICAO Doc 9432; Annex 3",
      },
      {
        id: "altimeter",
        title: "Altimeter Setting",
        when: "QNH makes the altimeter read altitude above mean sea level; QFE reads height above the aerodrome. Settings are in hectopascals, read digit by digit, and must be read back.",
        pilot: "QNH [digits] [Callsign]",
        atc: "[Callsign] QNH [digits]",
        convo: [A("WEONE 214, QNH 1009"), P("QNH 1009, WEONE 214")],
        notes: ["Some authorities require the word \"hectopascals\" when the setting is below 1000, to avoid confusion with inches of mercury."],
        ref: "ICAO Doc 9432: altimeter setting",
      },
      {
        id: "pirep",
        title: "Special Air-Report (Turbulence, Icing)",
        when: "Report hazardous weather you meet, such as severe turbulence, severe icing or wind shear, so ATC can warn others.",
        pilot: "[Station] [Callsign] SPECIAL AIR-REPORT [phenomenon] [position] [level] [time]",
        atc: "[Callsign] ROGER",
        convo: [P("Chennai Control, WEONE 214, special air-report, severe turbulence, 20 miles south of TELIM, FL310, time 0648"), A("WEONE 214, roger, thank you")],
        notes: ["Wind shear on approach should be reported to Tower straight away with the height and effect."],
        ref: "ICAO Doc 9432: special air-reports",
      },
    ],
  },
  {
    id: "emergency",
    title: "Emergency & Abnormal",
    icon: "alert",
    topics: [
      {
        id: "mayday",
        title: "Distress (MAYDAY)",
        when: "Grave and imminent danger requiring immediate help, such as fire, engine failure in a critical phase, or loss of control. Send it on the frequency in use.",
        pilot: "MAYDAY MAYDAY MAYDAY [Station] [Callsign] [nature] [intentions] [position, level, heading] [other info]",
        atc: "[Callsign] ROGER MAYDAY [instructions]",
        convo: [
          P("MAYDAY MAYDAY MAYDAY, Hyderabad Tower, WEONE 214, engine fire, returning to land, 5 miles west, 3000 feet, heading 090, 142 persons on board"),
          A("WEONE 214, roger MAYDAY, runway 27 cleared to land, wind 270 degrees 10 knots, emergency services alerted"),
          P("Cleared to land runway 27, WEONE 214"),
        ],
        notes: [
          "Set squawk 7700 unless already on an assigned code with ATC.",
          "Give as much of the message as time allows; the MAYDAY call itself comes first.",
          "Other stations keep silent unless they can help.",
        ],
        ref: "ICAO Doc 9432: distress messages; Annex 10 Vol II",
      },
      {
        id: "pan-pan",
        title: "Urgency (PAN PAN)",
        when: "A condition concerning the safety of the aircraft or a person on board that does not need immediate help, such as a sick passenger or a failed system.",
        pilot: "PAN PAN, PAN PAN, PAN PAN [Station] [Callsign] [nature] [intentions] [position, level]",
        atc: "[Callsign] ROGER PAN PAN [instructions]",
        convo: [
          P("PAN PAN, PAN PAN, PAN PAN, Mumbai Control, WEONE 318, passenger seriously ill, request priority landing Goa, FL330"),
          A("WEONE 318, roger PAN PAN, descend FL150, expect priority approach Goa"),
          P("Descend FL150, WEONE 318"),
        ],
        notes: ["Ask for the medical services you need on arrival."],
        ref: "ICAO Doc 9432: urgency messages",
      },
      {
        id: "cancel-distress",
        title: "Cancelling Distress or Urgency",
        when: "Once the situation is resolved, the aircraft cancels the MAYDAY or PAN PAN so the frequency returns to normal.",
        pilot: "[Station] [Callsign] CANCEL MAYDAY / CANCEL PAN PAN [reason]",
        atc: "[Callsign] ROGER",
        convo: [P("Hyderabad Tower, WEONE 214, fire extinguished, cancel MAYDAY"), A("WEONE 214, roger, MAYDAY cancelled")],
        notes: [],
        ref: "ICAO Doc 9432: distress messages",
      },
      {
        id: "imposing-silence",
        title: "Imposing Silence",
        when: "The station controlling distress traffic may order all other stations to stop transmitting, and later cancel that order.",
        pilot: "(comply; do not acknowledge unless asked)",
        atc: "ALL STATIONS, STOP TRANSMITTING, MAYDAY / DISTRESS TRAFFIC ENDED",
        convo: [A("All stations, Hyderabad Tower, stop transmitting, MAYDAY"), A("All stations, Hyderabad Tower, distress traffic ended")],
        notes: [],
        ref: "ICAO Doc 9432: distress messages",
      },
      {
        id: "mayday-relay",
        title: "MAYDAY RELAY",
        when: "Used by a station that hears a distress call which has not been acknowledged, or whose sender cannot transmit.",
        pilot: "MAYDAY RELAY MAYDAY RELAY MAYDAY RELAY [Station] [own Callsign] [distress message]",
        atc: "[Callsign] ROGER MAYDAY RELAY",
        convo: [P("MAYDAY RELAY, MAYDAY RELAY, MAYDAY RELAY, Chennai Control, WEONE 214, heard VT-WXD MAYDAY, engine failure, 10 miles east of PENAK, descending through FL90"), A("WEONE 214, roger MAYDAY RELAY")],
        notes: [],
        ref: "ICAO Doc 9432: distress messages",
      },
      {
        id: "squawk-codes",
        title: "Emergency Transponder Codes",
        when: "Three codes carry special meaning. Set them when needed unless ATC has already given you a code.",
        pilot: "SQUAWK [code]",
        atc: "[Callsign] CONFIRM SQUAWK [code]",
        convo: [A("WEONE 214, confirm squawking 7500"), P("Affirm, WEONE 214")],
        notes: ["7700: emergency. 7600: radio communication failure. 7500: unlawful interference.", "Avoid passing through 7500 or 7700 when changing codes."],
        ref: "ICAO Doc 4444 (PANS-ATM); Doc 8168",
      },
      {
        id: "minimum-fuel",
        title: "Minimum Fuel",
        when: "Tells ATC that any further delay could leave you landing with less than final reserve fuel. It is not an emergency; MAYDAY FUEL is used when the calculated fuel on landing is below final reserve.",
        pilot: "[Station] [Callsign] MINIMUM FUEL",
        atc: "[Callsign] ROGER [expected delay]",
        convo: [P("Chennai Approach, WEONE 214, minimum fuel"), A("WEONE 214, roger, no delay expected")],
        notes: [],
        ref: "ICAO Annex 6 Part I; Doc 4444",
      },
    ],
  },
  {
    id: "commfail",
    title: "Communication Failure",
    icon: "wifi-off",
    topics: [
      {
        id: "transmitting-blind",
        title: "Transmitting Blind",
        when: "If you cannot establish contact, transmit your messages twice on the frequency in use, starting with \"transmitting blind\". Include the time of your next intended transmission.",
        pilot: "TRANSMITTING BLIND [Station] [Callsign] [message] [message repeated]",
        atc: "(none expected)",
        convo: [P("Transmitting blind, Chennai Control, WEONE 214, FL330, estimating PENAK 0706, squawking 7600, I say again, FL330, estimating PENAK 0706, squawking 7600")],
        notes: ["Set squawk 7600 and keep listening on the frequency in use."],
        ref: "ICAO Annex 10 Vol II: communication failure",
      },
      {
        id: "receiver-failure",
        title: "Receiver Failure",
        when: "If you believe only your receiver has failed, transmit blind with \"transmitting blind due receiver failure\" and give the time of your next transmission.",
        pilot: "TRANSMITTING BLIND DUE RECEIVER FAILURE [Station] [Callsign] [message]",
        atc: "(ATC may reply using transponder instructions)",
        convo: [P("Transmitting blind due receiver failure, Chennai Approach, WEONE 214, 10 miles east SAVRI, 5000 feet, next transmission 0731")],
        notes: [],
        ref: "ICAO Annex 10 Vol II: communication failure",
      },
      {
        id: "atc-checks-rcf",
        title: "ATC Checking Radio Failure",
        when: "When ATC suspects your radio has failed they ask you to reply with a transponder action or a turn, so you can answer without transmitting.",
        pilot: "(respond with the requested action)",
        atc: "[Callsign] REPLY NOT RECEIVED. IF YOU READ, SQUAWK IDENT / TURN LEFT [heading]",
        convo: [A("WEONE 214, reply not received, if you read, squawk ident"), A("WEONE 214, squawk observed, will continue to pass instructions")],
        notes: [],
        ref: "ICAO Doc 4444 (PANS-ATM)",
      },
      {
        id: "rcf-procedure",
        title: "Procedure After Failure",
        when: "In visual conditions, continue in VMC, land at the nearest suitable aerodrome and report arrival. In instrument conditions, follow the published or ICAO lost-communication procedure.",
        pilot: "(no transmission required)",
        atc: "(ATC keeps airspace clear along your expected route)",
        convo: [P("Transmitting blind, Chennai Approach, WEONE 214, radio failure, continuing VMC, landing Chennai")],
        notes: [
          "In a radar environment the standard ICAO procedure is to keep the last assigned speed and level, or the minimum flight altitude if higher, for 7 minutes, then follow the flight plan.",
          "Always check the national AIP: local procedures take precedence.",
        ],
        ref: "ICAO Annex 2; Doc 4444 (PANS-ATM)",
      },
    ],
  },
  {
    id: "diversion",
    title: "Diversion",
    icon: "shuffle",
    topics: [
      {
        id: "request-diversion",
        title: "Request Diversion",
        when: "Used when you decide to land somewhere other than the planned destination because of weather, a technical problem, a medical case or fuel.",
        pilot: "[Station] [Callsign] REQUEST DIVERSION TO [aerodrome] DUE [reason]",
        atc: "[Callsign] CLEARED TO [aerodrome] VIA [route] [level]",
        convo: [P("Chennai Control, WEONE 214, weather below minima at Chennai, request diversion to Bengaluru"), A("WEONE 214, cleared to Bengaluru via direct PENAK, then flight planned route, maintain FL150"), P("Cleared to Bengaluru, direct PENAK then flight planned route, maintain FL150, WEONE 214")],
        notes: ["Tell ATC your endurance if it may affect priority."],
        ref: "ICAO Doc 9432: area control",
      },
      {
        id: "return-departure",
        title: "Return to Departure Aerodrome",
        when: "After a problem soon after take-off, request a return and state whether you need any assistance.",
        pilot: "[Station] [Callsign] REQUEST RETURN TO [aerodrome] DUE [reason]",
        atc: "[Callsign] [vectors / approach]",
        convo: [P("Hyderabad Departure, WEONE 214, landing gear unsafe indication, request return to Hyderabad"), A("WEONE 214, turn right heading 090, descend 4000 feet, vectors ILS runway 27"), P("Right heading 090, descend 4000 feet, WEONE 214")],
        notes: [],
        ref: "ICAO Doc 9432: approach control",
      },
    ],
  },
];



// ICAO location indicators for major Indian aerodromes. Always confirm against the current AIP India.
export const AIRPORTS = [
  { icao: "VIDP", city: "Delhi", name: "Indira Gandhi International" },
  { icao: "VABB", city: "Mumbai", name: "Chhatrapati Shivaji Maharaj International" },
  { icao: "VOBL", city: "Bengaluru", name: "Kempegowda International" },
  { icao: "VOMM", city: "Chennai", name: "Chennai International" },
  { icao: "VECC", city: "Kolkata", name: "Netaji Subhas Chandra Bose International" },
  { icao: "VOHS", city: "Hyderabad", name: "Rajiv Gandhi International" },
  { icao: "VAAH", city: "Ahmedabad", name: "Sardar Vallabhbhai Patel International" },
  { icao: "VOCI", city: "Kochi", name: "Cochin International" },
  { icao: "VOGO", city: "Goa (Dabolim)", name: "Goa International" },
  { icao: "VOGA", city: "Goa (Mopa)", name: "Manohar International" },
  { icao: "VAPO", city: "Pune", name: "Pune" },
  { icao: "VILK", city: "Lucknow", name: "Chaudhary Charan Singh International" },
  { icao: "VIJP", city: "Jaipur", name: "Jaipur International" },
  { icao: "VEGT", city: "Guwahati", name: "Lokpriya Gopinath Bordoloi International" },
  { icao: "VOTV", city: "Thiruvananthapuram", name: "Thiruvananthapuram International" },
  { icao: "VOCB", city: "Coimbatore", name: "Coimbatore International" },
  { icao: "VIAR", city: "Amritsar", name: "Sri Guru Ram Dass Jee International" },
  { icao: "VEBS", city: "Bhubaneswar", name: "Biju Patnaik International" },
  { icao: "VANP", city: "Nagpur", name: "Dr. Babasaheb Ambedkar International" },
  { icao: "VOVZ", city: "Visakhapatnam", name: "Visakhapatnam" },
  { icao: "VOML", city: "Mangaluru", name: "Mangaluru International" },
  { icao: "VEPT", city: "Patna", name: "Jay Prakash Narayan" },
  { icao: "VEBN", city: "Varanasi", name: "Lal Bahadur Shastri International" },
  { icao: "VIDN", city: "Dehradun", name: "Jolly Grant" },
  { icao: "VISR", city: "Srinagar", name: "Srinagar" },
  { icao: "VILH", city: "Leh", name: "Kushok Bakula Rimpochee" },
  { icao: "VEPB", city: "Port Blair", name: "Veer Savarkar International" },
  { icao: "VICG", city: "Chandigarh", name: "Shaheed Bhagat Singh International" },
];



export const PHRASE_QA = [
  { q: "What does ROGER mean, and when is it not enough?", a: "\"I have received all of your last transmission.\" It is never a readback of a clearance and never answers a yes/no question." },
  { q: "What is the difference between CONTACT and MONITOR?", a: "CONTACT: establish two-way communication with the station. MONITOR: listen on the frequency without calling." },
  { q: "Why does a pilot say \"ready for departure\" and not \"ready for take-off\"?", a: "The words \"take-off\" are reserved for the take-off clearance and its cancellation, to prevent a readiness report being heard as a clearance." },
  { q: "How is FL100 spoken?", a: "\"Flight level wun zero zero\"; flight levels are always digit by digit." },
  { q: "How is an altitude of 11,000 ft spoken?", a: "\"One one tousand feet\"." },
  { q: "Say the frequency 118.025 MHz.", a: "\"One one eight decimal zero two fife\"." },
  { q: "What word means \"Examine a system or procedure\"?", a: "CHECK. No answer is normally expected." },
  { q: "What word means \"An error has been made in this transmission; the correct version is...\"?", a: "CORRECTION." },
  { q: "What word separates portions of a message?", a: "BREAK. BREAK BREAK separates messages to different aircraft in a busy environment." },
  { q: "What does APPROVED mean?", a: "Permission for the proposed action is granted." },
  { q: "What does CLEARED mean?", a: "Authorised to proceed under the conditions specified." },
  { q: "What does CONFIRM mean?", a: "\"I request verification of (clearance, instruction, action, information).\"" },
  { q: "What does ACKNOWLEDGE mean?", a: "\"Let me know that you have received and understood this message.\"" },
  { q: "What does SAY AGAIN replace, and why?", a: "It replaces \"repeat\" when asking for a transmission to be sent again, because \"repeat\" has a different military meaning." },
  { q: "How many times is MAYDAY said at the start of a distress call?", a: "Three times: MAYDAY MAYDAY MAYDAY." },
  { q: "How is PAN PAN transmitted?", a: "Three times: PAN PAN, PAN PAN, PAN PAN." },
];
