export const chapters = [
  {
    id: 'rt01',
    title: 'RT Procedures and Phraseology',
    icon: '📻',
    part: 'Radio Telephony',
    color: '#8B5CF6',
  },
  {
    id: 'rt02',
    title: 'Departure, En-Route and Approach RT',
    icon: '🛫',
    part: 'Radio Telephony',
    color: '#8B5CF6',
  },
  {
    id: 'rt03',
    title: 'Emergency and Special Procedures',
    icon: '🚨',
    part: 'Radio Telephony',
    color: '#8B5CF6',
  },
]

export const questions = {
  rt01: [
    {
      id: 'rt01_01',
      question: 'A pilot should use standard phraseology mainly to:',
      options: ['ensure clarity and reduce misunderstanding', 'increase speed', 'reduce fuel use', 'improve cabin comfort'],
      correct: 0,
      explanation: 'Standard phraseology improves clarity and reduces misunderstanding in radio communications.',
    },
    {
      id: 'rt01_02',
      question: 'When a pilot receives an instruction, the pilot should:',
      options: ['acknowledge and comply as required', 'ignore it if busy', 'turn off the radio', 'descend immediately'],
      correct: 0,
      explanation: 'Pilots must acknowledge and comply with radio instructions unless they are unable to do so.',
    },
    {
      id: 'rt01_03',
      question: 'A read-back is used mainly to:',
      options: ['confirm the understood instruction', 'reduce radio traffic', 'increase altitude', 'save fuel'],
      correct: 0,
      explanation: 'Read-back confirms that the pilot has understood the instruction correctly.',
    },
    {
      id: 'rt01_04',
      question: 'The purpose of phraseology is to:',
      options: ['standardize communication', 'replace ATC', 'reduce weather', 'increase payload'],
      correct: 0,
      explanation: 'Phraseology standardizes radio communication and reduces ambiguity.',
    },
    {
      id: 'rt01_05',
      question: 'A pilot should speak clearly on the radio because:',
      options: ['poor transmission can cause errors', 'clear speech increases fuel burn', 'ATC prefers long messages', 'radio traffic should be ignored'],
      correct: 0,
      explanation: 'Clear radio transmission minimizes misunderstandings and operational errors.',
    },
    {
      id: 'rt01_06',
      question: 'A pilot should avoid unnecessary words on the radio because:',
      options: ['it keeps communications concise', 'it increases workload', 'it reduces safety', 'it replaces read-back'],
      correct: 0,
      explanation: 'Concise radio traffic keeps channels clear and reduces confusion.',
    },
    {
      id: 'rt01_07',
      question: 'When a pilot needs to state a problem, the pilot should:',
      options: ['report it promptly and clearly', 'wait until landing', 'turn off the radio', 'ask the passengers'],
      correct: 0,
      explanation: 'Prompt and clear reporting helps ATC provide timely assistance.',
    },
    {
      id: 'rt01_08',
      question: 'The radio frequency should be selected correctly mainly to:',
      options: ['ensure contact with the proper unit', 'change the weather', 'reduce cabin pressure', 'improve fuel economy'],
      correct: 0,
      explanation: 'Selecting the correct frequency ensures communication with the appropriate ATC unit.',
    },
    {
      id: 'rt01_09',
      question: 'A pilot should maintain a listening watch to:',
      options: ['hear relevant instructions and traffic', 'reduce altitude', 'raise the flaps', 'avoid the runway'],
      correct: 0,
      explanation: 'Listening watch helps the pilot receive relevant instructions and traffic information.',
    },
    {
      id: 'rt01_10',
      question: 'A radio call should be made at the right time to:',
      options: ['avoid disturbing other traffic', 'increase drag', 'reduce visibility', 'lower altitude'],
      correct: 0,
      explanation: 'Timely calls help maintain order and avoid unnecessary congestion on the frequency.',
    },
  ],
  rt02: [
    {
      id: 'rt02_01',
      question: 'A departure clearance is used to:',
      options: ['authorize the aircraft to depart under specified conditions', 'reduce engine power', 'change the runway lights', 'close the frequency'],
      correct: 0,
      explanation: 'A departure clearance authorizes the aircraft to depart under the specified conditions.',
    },
    {
      id: 'rt02_02',
      question: 'A pilot should report passing a specified point mainly to:',
      options: ['inform ATC of progress', 'reduce fuel flow', 'change heading', 'turn off the radio'],
      correct: 0,
      explanation: 'Position reports inform ATC of the aircraft’s progress and current status.',
    },
    {
      id: 'rt02_03',
      question: 'An approach call is made to:',
      options: ['inform ATC that the aircraft is arriving', 'begin taxiing', 'increase passenger load', 'cancel the flight plan'],
      correct: 0,
      explanation: 'An approach call informs ATC that the aircraft is commencing the approach.',
    },
    {
      id: 'rt02_04',
      question: 'A pilot should report leaving the holding pattern when:',
      options: ['the aircraft starts to continue the route', 'the weather becomes VFR', 'the engines are shut down', 'the runway is wet'],
      correct: 0,
      explanation: 'Leaving the hold is a significant change in status that should be reported.',
    },
    {
      id: 'rt02_05',
      question: 'A pilot should use the correct call sign because:',
      options: ['it identifies the aircraft accurately', 'it improves fuel economy', 'it reduces cabin pressure', 'it lowers altitude'],
      correct: 0,
      explanation: 'The call sign identifies the aircraft and ensures correct communications.',
    },
    {
      id: 'rt02_06',
      question: 'During en-route flight, a position report usually includes:',
      options: ['position, time, and altitude', 'seat number, crew name, and fuel price', 'weather only', 'landing gear status only'],
      correct: 0,
      explanation: 'Position reports normally include the aircraft’s position, time, and altitude information.',
    },
    {
      id: 'rt02_07',
      question: 'A pilot should call approach control before entering the approach sequence because:',
      options: ['ATC needs to coordinate the operation', 'the aircraft must slow down', 'the passengers need food', 'the runway must be closed'],
      correct: 0,
      explanation: 'Approach control coordinates and manages the aircraft’s arrival sequence.',
    },
    {
      id: 'rt02_08',
      question: 'A pilot should maintain a proper listening watch in the terminal area because:',
      options: ['instructions and traffic information may change quickly', 'the landing lights are switched off', 'the aircraft weight is reduced', 'the runway is closed'],
      correct: 0,
      explanation: 'Traffic and instructions may change quickly in terminal areas.',
    },
    {
      id: 'rt02_09',
      question: 'A pilot should report a missed approach because:',
      options: ['ATC needs to know the aircraft is not landing', 'the cabin crew needs to be alerted', 'the fuel quantity is low', 'the engine sound changes'],
      correct: 0,
      explanation: 'A missed approach changes the aircraft’s intended operation and needs ATC awareness.',
    },
    {
      id: 'rt02_10',
      question: 'Good RT discipline during departure and arrival helps:',
      options: ['maintain safety and order', 'increase drag', 'reduce cabin pressure', 'avoid weather'],
      correct: 0,
      explanation: 'Good radio discipline supports safe and orderly operations at departure and arrival.',
    },
  ],
  rt03: [
    {
      id: 'rt03_01',
      question: 'In an emergency, a pilot should make the distress call as soon as:',
      options: ['the situation requires immediate assistance', 'the weather clears', 'the passengers settle', 'the aircraft lands'],
      correct: 0,
      explanation: 'A distress call is made when immediate assistance is needed.',
    },
    {
      id: 'rt03_02',
      question: 'A pilot should use urgency calls when:',
      options: ['there is a serious but not immediate danger', 'the aircraft is at cruise', 'the runway is clear', 'the cabin is empty'],
      correct: 0,
      explanation: 'Urgency calls are used for situations needing priority but not immediate distress.',
    },
    {
      id: 'rt03_03',
      question: 'A pilot should report a radio failure because:',
      options: ['ATC needs to know the aircraft may be unable to communicate normally', 'the passengers need to know', 'the weather is good', 'the airport is open'],
      correct: 0,
      explanation: 'A radio failure affects the aircraft’s ability to communicate and requires ATC awareness.',
    },
    {
      id: 'rt03_04',
      question: 'If unable to comply with an ATC instruction, the pilot should:',
      options: ['inform ATC as soon as possible', 'continue silently', 'switch off the engine', 'descend without clearance'],
      correct: 0,
      explanation: 'A pilot must inform ATC if unable to comply with an instruction.',
    },
    {
      id: 'rt03_05',
      question: 'A pilot should use a distress call rather than a routine call when:',
      options: ['immediate assistance is required', 'the aircraft is taxiing', 'the weather is VFR', 'the passengers are seated'],
      correct: 0,
      explanation: 'Distress calls are reserved for situations requiring immediate assistance.',
    },
    {
      id: 'rt03_06',
      question: 'Good radio discipline in an emergency helps to:',
      options: ['keep communications clear and effective', 'reduce cabin noise', 'increase aircraft weight', 'hide the problem'],
      correct: 0,
      explanation: 'Clear radio discipline improves the effectiveness of emergency communications.',
    },
    {
      id: 'rt03_07',
      question: 'A pilot should maintain the emergency frequency only when:',
      options: ['it is necessary for the emergency', 'the aircraft is on the ground', 'the weather is good', 'the passengers are asleep'],
      correct: 0,
      explanation: 'The emergency frequency should be used only for essential emergency communications.',
    },
    {
      id: 'rt03_08',
      question: 'A pilot should report a medical emergency because:',
      options: ['it can trigger priority assistance', 'it saves fuel', 'it reduces workload', 'it improves weather'],
      correct: 0,
      explanation: 'Medical emergencies may require priority assistance from ATC and rescue services.',
    },
    {
      id: 'rt03_09',
      question: 'In an emergency, the pilot should keep the message:',
      options: ['short, clear, and informative', 'long and vague', 'silent and private', 'personal and emotional'],
      correct: 0,
      explanation: 'Emergency messages should be short, clear, and informative.',
    },
    {
      id: 'rt03_10',
      question: 'A pilot should continue to monitor the frequency in an emergency to:',
      options: ['receive updated instructions', 'reduce cabin pressure', 'close the flight plan', 'save fuel'],
      correct: 0,
      explanation: 'Monitoring the frequency allows the pilot to receive updated instructions and information.',
    },
  ],
}
