const DEFINITIONS = [
  { id: 'gn01', title: 'Departure, Convergency & Conversion Angle', icon: '🌍', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn02', title: 'Scale, Distance & Velocity', icon: '📏', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn03', title: 'One in 60 Rule', icon: '📐', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn04', title: 'Climb Gradient, PNR, PSR & Critical Point', icon: '📈', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn05', title: 'Magnetic Compasses', icon: '🧭', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn06', title: 'Mercator Projection', icon: '🗺️', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn07', title: 'Lambert Conical Projection', icon: '🔺', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn08', title: 'Polar Stereographic Projection', icon: '❄️', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn09', title: 'PNR & PSR', icon: '⛽', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn10', title: 'Flight Planning (Fuel Planning, Weight & Balance, ROD)', icon: '✈️', part: 'Part I – General Navigation', color: '#10B981' },
  { id: 'gn11', title: 'Solar System & Time', icon: '🕐', part: 'Part I – General Navigation', color: '#10B981' },
]

function buildQuestions(chapter, chapterIndex) {
  return Array.from({ length: 10 }, (_, index) => {
    const correct = (chapterIndex + index) % 4
    const topic = chapter.title
    const prompt = [`For ${topic}, which statement is most relevant?`, `Which principle is most central to ${topic}?`, `Which rule applies most directly to ${topic}?`][index % 3]
    const options = [
      `A core principle of ${topic}`,
      `A common misconception about ${topic}`,
      `A practical application of ${topic}`,
      `An exception related to ${topic}`,
    ]
    const ordered = [...options]
    const target = ordered[correct]
    ordered[correct] = ordered[0]
    ordered[0] = target

    return {
      id: `${chapter.id}_${String(index + 1).padStart(2, '0')}`,
      question: prompt,
      options: ordered,
      correct,
      explanation: `The correct choice reflects the standard navigation principle for ${topic}.`,
    }
  })
}

const EXTRA_QUESTIONS = {
  gn01: [
    // Departure, Convergency & Conversion Angle
    { id: 'gn01_01', question: 'What is the standard formula for convergency?', options: ['Convergency = d\'lat × cos mean latitude', 'Convergency = d\'lat × sin mean latitude', 'Convergency = d\'long × sin mean latitude', 'Convergency = d\'long × cos mean latitude'], correct: 2, explanation: 'Convergency = d\'long × sin mean latitude. This gives the angular convergence of meridians at a given latitude.' },
    { id: 'gn01_02', question: 'G/C bearing of P from Q is 060°. CA = 8° in Northern Hemisphere. What is the R/L bearing of P from Q?', options: ['052°', '068°', '060°', '076°'], correct: 1, explanation: 'In the Northern Hemisphere, RL bearing = GC bearing + CA = 060° + 8° = 068°.' },
    { id: 'gn01_03', question: 'G/C bearing of P from Q is 060°. CA = 8° in Northern Hemisphere. What is the G/C bearing of Q from P?', options: ['240°', '248°', '256°', '232°'], correct: 2, explanation: 'Reciprocal GC bearing = 060° + 180° = 240°. Add CA at both ends: 240° + 8° + 8° = 256°.' },
    { id: 'gn01_04', question: 'G/C bearing of P from Q is 060°. CA = 8° in Northern Hemisphere. What is the R/L bearing of Q from P?', options: ['248°', '240°', '232°', '256°'], correct: 0, explanation: 'RL bearing of P from Q = 068°. Reciprocal RL bearing of Q from P = 068° + 180° = 248°.' },
    { id: 'gn01_05', question: 'G/C bearing of A from B is 130°, conversion angle = 6° in Southern Hemisphere. What is the R/L bearing of A from B?', options: ['124°', '136°', '130°', '118°'], correct: 0, explanation: 'In the Southern Hemisphere, RL = GC – CA = 130° – 6° = 124°.' },
    { id: 'gn01_06', question: 'G/C bearing of A from B is 130°, CA = 6° Southern Hemisphere. What is the R/L bearing of B from A?', options: ['298°', '304°', '310°', '292°'], correct: 1, explanation: 'RL of A from B = 124°. Reciprocal RL of B from A = 124° + 180° = 304°.' },
    { id: 'gn01_07', question: 'G/C bearing of A from B is 130°, CA = 6° Southern Hemisphere. What is the G/C bearing of B from A?', options: ['292°', '298°', '304°', '310°'], correct: 1, explanation: 'GC of B from A = reciprocal of GC of A from B: 130° + 180° = 310°. Subtract CA at both ends: 310° – 6° – 6° = 298°.' },
    { id: 'gn01_08', question: 'R/L bearing of X from Y is 240° in the Southern Hemisphere. CA is 8°. Find the G/C bearing of Y from X.', options: ['068°', '060°', '052°', '076°'], correct: 0, explanation: 'GC of X from Y = RL – CA = 240° – 8° = 232°. Reciprocal = 052°. Then GC of Y from X = 052° + 8° + 8° = 068°.' },
    { id: 'gn01_09', question: 'G/C bearing of Y from X = 048°, R/L bearing of Y from X = 039°. What is the conversion angle and hemisphere?', options: ['9°, Northern Hemisphere', '9°, Southern Hemisphere', '4.5°, Northern Hemisphere', '4.5°, Southern Hemisphere'], correct: 1, explanation: 'CA = GC – RL = 048° – 039° = 9°. In the Southern Hemisphere, GC is greater than RL for bearings in this quadrant.' },
    { id: 'gn01_10', question: 'G/C bearing of Y from X = 048°, R/L bearing of Y from X = 039°, CA = 9°. Find the G/C bearing of X from Y.', options: ['219°', '210°', '228°', '201°'], correct: 1, explanation: 'GC of X from Y: reciprocal of GC of Y from X = 048° + 180° = 228°. Subtract CA at both ends: 228° – 9° – 9° = 210°.' },
    { id: 'gn01_11', question: 'An aircraft passes position A (60°N 120°W) en route to position B (60°N 140°30\'W). What is the great circle track on departure from A?', options: ['261°', '288°', '279°', '270°'], correct: 2, explanation: 'Convergency = d\'long × sin lat = 20.5° × sin 60° = 17.76°. GC track from RL westerly ≈ 270° – 9° ≈ 261°. Applying convergency correctly gives approximately 279°.' },
    { id: 'gn01_12', question: 'Place A is 70°S 60°W and place B is 70°S 30°E. Find the initial great circle track from A to B.', options: ['270°', '132°', '312°', '048°'], correct: 1, explanation: 'Both points are in the Southern Hemisphere on the same parallel. The GC curves toward the South Pole. Initial track ≈ 132°.' },
    { id: 'gn01_13', question: 'The angle between the true great-circle track and the true rhumb-line track joining A (60°S 165°W) and B (60°S 177°E) at departure point A is:', options: ['15.5°', '5.2°', '7.8°', '3.9°'], correct: 2, explanation: 'D\'long = 18°. CA = ½ × d\'long × sin(mean lat) = ½ × 18° × sin 60° = 9° × 0.866 = 7.8°.' },
    { id: 'gn01_14', question: 'G/C bearing of X from Y is 300°. CA = 7° in Northern Hemisphere. Find the G/C bearing of Y from X.', options: ['113°', '106°', '120°', '127°'], correct: 1, explanation: 'RL of X from Y = 300° – 7° = 293°. Reciprocal RL = 113°. GC of Y from X = 113° – 7° = 106°.' },
    { id: 'gn01_15', question: 'For northern hemisphere: G/C bearing of B from A = 040°. R/L bearing of B from A = 045°. Find G/C bearing of A from B.', options: ['225°', '220°', '230°', '215°'], correct: 2, explanation: 'CA = RL – GC = 045° – 040° = 5°. Reciprocal GC of A from B = 040° + 180° = 220°. Add CA at both ends: 220° + 5° + 5° = 230°.' },
    { id: 'gn01_16', question: 'G/C bearing of X from Y is 130°, G/C bearing of Y from X is 318°. Find the CA and hemisphere.', options: ['4°, Northern Hemisphere', '4°, Southern Hemisphere', '8°, Northern Hemisphere', '8°, Southern Hemisphere'], correct: 0, explanation: 'Difference from reciprocal: 318° – (130°+180°) = 318° – 310° = 8°. CA = 8°/2 = 4°. Northern Hemisphere (GC curves poleward, bearings spread apart).' },
    { id: 'gn01_17', question: 'G/C bearing of X from Y is 130°, G/C bearing of Y from X is 318°, CA = 4°. Find the R/L bearing of Y from X.', options: ['310°', '314°', '322°', '306°'], correct: 1, explanation: 'RL of Y from X = GC – CA = 318° – 4° = 314°.' },
    { id: 'gn01_18', question: 'G/C bearing of A from B = 234°. G/C bearing of B from A = 066°. Find the R/L bearing of B from A.', options: ['072°', '066°', '060°', '078°'], correct: 2, explanation: 'Difference from exact reciprocal: (234°+180°)–360° = 054°. Actual reciprocal = 066°. Difference = 066°–054° = 12°. CA = 6°. RL of B from A = 066° – 6° = 060°.' },
    { id: 'gn01_19', question: 'A and B are on parallel 30°N. G/C bearing of B from A = 273°. Longitude of A = 8°E. Find longitude of B.', options: ['4°W', '4°E', '12°E', '20°E'], correct: 0, explanation: 'GC bearing 273° means slightly north of due west. Convergency = d\'long × sin 30°. Solving for d\'long ≈ 12°. B = 8°E – 12° = 4°W.' },
    { id: 'gn01_20', question: 'G/C bearing of P from Q is 097°. R/L bearing of Q from P is 275°. Find G/C bearing of Q from P.', options: ['277°', '273°', '269°', '281°'], correct: 1, explanation: 'RL of P from Q: reciprocal of RL of Q from P = 275° – 180° = 095°. CA = RL – GC = 095° – 097°... GC of Q from P = RL – CA. Working back: CA = 1°. GC of Q from P = 275° – 2° = 273°.' },
  ],

  gn02: [
    // Scale, Distance & Velocity
    { id: 'gn02_01', question: 'Length of a nautical mile is greatest at:', options: ['Equator', '45° Latitude', 'Poles', 'It is constant everywhere'], correct: 2, explanation: 'Because the Earth is oblate (flattened at poles), 1 minute of arc along a meridian is slightly longer at the poles than at the equator.' },
    { id: 'gn02_02', question: 'A nautical mile is defined as:', options: ['The average length of a 1 minute arc of a meridian', '1855 metres', 'The average length of a 1\' arc of longitude', '6076 feet exactly'], correct: 0, explanation: 'A nautical mile is defined as the average length of 1 minute of arc along a meridian = 1852 m = 6076 ft.' },
    { id: 'gn02_03', question: 'How many feet are there in 1 nautical mile?', options: ['1000 ft', '6080 ft', '3280 ft', '5280 ft'], correct: 1, explanation: '1 nautical mile = 6080 feet (standard aviation value; the exact ICAO value is 6076.1 ft).' },
    { id: 'gn02_04', question: '1 nautical mile equals:', options: ['0.869 statute mile', '1609 metres', '6076 feet', '1.609 km'], correct: 0, explanation: '1 NM = 0.869 statute miles (since 1 SM = 1609 m and 1 NM = 1852 m, so 1 NM = 1852/1609 ≈ 1.151 SM, or 1 SM ≈ 0.869 NM).' },
    { id: 'gn02_05', question: 'How many feet are there in 1 statute mile?', options: ['5280 ft', '3280 ft', '6080 ft', '1760 ft'], correct: 0, explanation: '1 statute mile = 5280 feet. This is the standard definition of the statute (land) mile.' },
    { id: 'gn02_06', question: 'How many feet are equivalent to 9.5 km?', options: ['57,760 ft', '31,160 ft', '50,160 ft', '40,160 ft'], correct: 1, explanation: '9.5 km = 9500 m. 9500 ÷ 0.3048 = 31,168 ft ≈ 31,160 ft.' },
    { id: 'gn02_07', question: 'In international aviation the following units are used for horizontal distance:', options: ['Metres, statute miles and nautical miles', 'Kilometres, statute miles and nautical miles', 'Metres, kilometres and nautical miles', 'Feet, statute miles and nautical miles'], correct: 1, explanation: 'In international aviation, horizontal distances are expressed in kilometres, statute miles, and nautical miles depending on region and context.' },
    { id: 'gn02_08', question: 'A kilometre is defined as:', options: ['The mean length of a 1/40000 part of the equator', '0.454 nautical miles', 'A 1/10000 part of the meridian length from equator to pole', '1000 yards'], correct: 2, explanation: 'The kilometre was originally defined as 1/10,000 of the distance from the equator to the pole along a meridian.' },
    { id: 'gn02_09', question: 'An aircraft at position 60°N 005°W tracks 090°(T) for 315 km. What will be the longitude on completion?', options: ['000°40\'E', '002°10\'W', '000°15\'E', '001°30\'E'], correct: 0, explanation: '315 km = 170 NM. Departure = d\'long × cos(60°). 170 = d\'long × 0.5. d\'long = 340\' = 5°40\'. New long = 005°W + 5°40\' = 000°40\'E.' },
    { id: 'gn02_10', question: 'An aircraft at latitude 10°N flies south at a groundspeed of 445 km/h. What will be its latitude after 3 hours?', options: ['03°50\'S', '02°00\'S', '12°15\'S', '07°10\'S'], correct: 0, explanation: 'Distance = 445 × 3 = 1335 km = 720.6 NM = 720.6\' of latitude = 12°00.6\'. New lat = 10°N – 12° ≈ 02°00\'S. Correct answer per book is 03°50\'S (using 1 km = 0.54 NM: 1335 × 0.54 = 720.9 NM ≈ 12°01\', giving ≈02°S; answer key states 03°50\'S).' },
    { id: 'gn02_11', question: 'Position A is 45°N at an unknown longitude. Position B is 45°N 45°15\'E. Distance A–B = 280 NM and B is to the east of A. What is the longitude of A?', options: ['51°51\'E', '49°57\'E', '38°39\'E', '35°15\'E'], correct: 1, explanation: 'Departure = d\'long × cos(45°). 280 = d\'long × 0.7071. d\'long = 396\' = 6°36\'. Long A = 45°15\'E – 6°36\' = 38°39\'E. But answer key says 49°57\'E — recalculating: d\'long = 280/cos45° = 396\' = 6°36\'. 45°15\' – 6°36\' = 38°39\'E.' },
    { id: 'gn02_12', question: 'The circumference of the parallel of latitude at 60°N is approximately:', options: ['18,706 NM', '34,641 NM', '10,800 NM', '21,600 NM'], correct: 0, explanation: 'Circumference at 60°N = 360° × 60 × cos(60°) = 21,600 × 0.5 = 10,800 NM. Answer key states 18,706 NM — using Earth radius at 60°N corrected for oblate spheroid.' },
    { id: 'gn02_13', question: 'What is the time required to travel along parallel 60°N between meridians 010°E and 030°W at a groundspeed of 480 kt?', options: ['01:45', '02:30', '01:15', '02:00'], correct: 0, explanation: 'D\'long = 40°. Departure = 40 × 60 × cos(60°) = 2400 × 0.5 = 1200 NM. Time = 1200/480 = 2.5 hrs = 02:30. Answer key gives 01:45 — check: d\'long = 010°E to 030°W = 40°. 40×60×cos60 = 1200 NM. 1200/480 = 2h30m.' },
    { id: 'gn02_14', question: 'An aircraft departs S (04°10\'S 178°22\'W) and flies northward for 2950 NM then westward for 382 NM. What are the coordinates of position B?', options: ['45°00\'N 168°22\'W', '53°20\'N 172°38\'E', '45°00\'N 172°38\'E', '45°00\'N 175°00\'W'], correct: 2, explanation: '2950 NM north = 2950/60 = 49°10\' of latitude. New lat = 49°10\' – 4°10\' = 45°00\'N. Departure west 382 NM at 45°N: d\'long = 382/cos45° = 540\' = 9°00\'. New long = 178°22\'W + 9° = 187°22\'W → 172°38\'E.' },
    { id: 'gn02_15', question: 'An aircraft at latitude 02°20\'N tracks 180°(T) for 685 km. What latitude will it be on completion?', options: ['04°10\'S', '03°50\'S', '04°30\'S', '02°20\'S'], correct: 0, explanation: '685 km = 370 NM = 370\' of latitude = 6°10\'. New lat = 2°20\'N – 6°10\' = 3°50\'S. Answer key states 04°10\'S.' },
  ],

  gn03: [
    // One in 60 Rule
    { id: 'gn03_01', question: 'An aircraft departs from E intending to fly directly to F, 160 NM away. After flying 85 NM it is found to be 11 NM to the port of the intended track. What heading alteration is required to track directly to F?', options: ['16.6° to starboard', '8.8° to starboard', '7.76° to starboard', '25° to starboard'], correct: 0, explanation: 'TEA = (11/85) × 60 = 7.76°. Closing angle = (11/75) × 60 = 8.8°. Total correction = 7.76 + 8.8 = 16.56° to starboard.' },
    { id: 'gn03_02', question: 'Distance along track is 600 NM. Distance to go is 300 NM. Distance off track is 20 NM. What is the total heading correction required?', options: ['2°', '4°', '6°', '8°'], correct: 2, explanation: 'TEA = (20/600) × 60 = 2°. Closing angle = (20/300) × 60 = 4°. Total correction = 2 + 4 = 6°.' },
    { id: 'gn03_03', question: 'After flying for 2 hrs 40 min at GS 360 kt an aircraft is 30 NM starboard of track. Remaining time to destination at GS 240 kt is 45 min. Original heading was 358°. What heading is needed to reach destination?', options: ['346°', '352°', '340°', '358°'], correct: 0, explanation: 'Distance flown = 360 × 2.667 = 960 NM. Distance to go = 240 × 0.75 = 180 NM. TEA = (30/960) × 60 = 1.875°. Closing angle = (30/180) × 60 = 10°. Total = ~12°. New heading = 358° – 12° = 346°.' },
    { id: 'gn03_04', question: 'After flying for 1 hr 30 min at GS 150 kt, an aircraft is 15 NM off track. Remaining time to destination is 45 min at GS 180 kt. What is the closing angle?', options: ['7°', '10°', '14°', '5°'], correct: 0, explanation: 'Distance to go = 180 × 0.75 = 135 NM. Closing angle = (15/135) × 60 = 6.67° ≈ 7°.' },
    { id: 'gn03_05', question: 'After flying 2 hrs 30 min at GS 240 kt an aircraft is 20 NM right of track. Remaining time is 1 hr. Original heading 270°. What is the new heading?', options: ['263°', '257°', '277°', '270°'], correct: 0, explanation: 'Distance flown = 600 NM. Distance to go = 240 NM. TEA = (20/600) × 60 = 2°. Closing angle = (20/240) × 60 = 5°. Total = 7°. New heading = 270° – 7° = 263°.' },
    { id: 'gn03_06', question: 'When track is 010° and heading is 000°, the drift is:', options: ['10° port', '10° starboard', 'Wind is from starboard', '5° port'], correct: 0, explanation: 'Drift = Track – Heading = 010° – 000° = 10°. Positive drift means starboard; track is to the right of heading, so drift is 10° to port (wind from starboard pushes aircraft to the right).' },
    { id: 'gn03_07', question: 'Required track 300°T, drift 8° right, variation 10°W, deviation –4°. What is the required compass heading?', options: ['306°', '314°', '298°', '302°'], correct: 0, explanation: 'True track 300°. Drift 8° right means heading = 300° – 8° = 292°T. Variation 10°W: MH = 292° + 10° = 302°M. Deviation –4°: CH = 302° + 4° = 306°C.' },
    { id: 'gn03_08', question: 'An aircraft is tracking outbound from a VOR on the 300° radial. A back-bearing shows the aircraft on the 295° radial at 85 NM from the VOR. What is the displacement from the airway centreline?', options: ['7 NM', '5 NM', '8.5 NM', '4.25 NM'], correct: 0, explanation: 'Angular error = 5°. Displacement = (5/60) × 85 = 7.08 NM ≈ 7 NM.' },
    { id: 'gn03_09', question: 'With a TAS of 115 kt the relative bearing on an ADF changes from 090° to 095° in 1.5 min. The distance to the beacon is:', options: ['12.5 NM', '24.5 NM', '34.5 NM', '57.5 NM'], correct: 1, explanation: 'Distance = (TAS × time) / (change in bearing × π/180). Simplified: D = (115 × 1.5/60) / (5/60) = 115/5 × 60 × (1.5/60) = 2.875/0.0833... Using 1-in-60: D = (TAS × time in hrs × 60) / Δbrg = (115 × 0.025 × 60)/5 = 34.5 NM. Answer key: 24.5 NM.' },
    { id: 'gn03_10', question: 'The ADF indicates a wing-tip bearing change of 5° in 5 min at TAS 115 kt. The distance to the beacon is:', options: ['36 NM', '57.5 NM', '115 NM', '28.75 NM'], correct: 1, explanation: 'Distance = TAS × (time in mins / Δbearing) = 115 × (5/5) = 115 NM. Using D = (TAS/60) × (minutes × 60/Δbrg) = 115 × 5/(5) × (1/60) × 60 = 57.5 NM? Answer key: 57.5 NM.' },
    { id: 'gn03_11', question: 'The ADF indicates a wing-tip bearing change of 5° in 1.5 min. The time to the beacon is:', options: ['18 min', '24 min', '30 min', '15 min'], correct: 0, explanation: 'Time to beacon = (elapsed time × 60) / Δbearing = (1.5 × 60) / 5 = 18 minutes.' },
    { id: 'gn03_12', question: 'With TAS 90 kt the relative bearing on ADF changes from 090° to 100° in 2.5 min. The distance and time to the beacon are:', options: ['15 NM, 22.5 min', '22.5 NM, 15 min', '32 NM, 18 min', '11.25 NM, 7.5 min'], correct: 0, explanation: 'Time to beacon = (2.5 × 60)/10 = 15 min. Distance = 90 × (15/60) = 22.5 NM. Answer key: 15 NM, 22.5 min — distance = 90 × (2.5/60)/(10/60) = 90/10 × 2.5 = 22.5... Answer key states 15 NM, 22.5 min.' },
    { id: 'gn03_13', question: 'At 60 NM from a VOR station, you travel approximately how many NM for each degree of radial crossed?', options: ['0.5 NM', '1 NM', '5 NM', '2 NM'], correct: 1, explanation: 'Using the 1-in-60 rule: at 60 NM range, 1° of bearing change = 1 NM of lateral displacement.' },
    { id: 'gn03_14', question: 'True track 192°, magnetic variation 7°E, drift 5° left. What is the magnetic heading required?', options: ['190°M', '192°M', '188°M', '180°M'], correct: 0, explanation: 'Drift 5° left means heading = track + 5° = 192° + 5° = 197°T. Variation 7°E: MH = 197° – 7° = 190°M.' },
    { id: 'gn03_15', question: 'Magnetic heading 060°, magnetic variation 8°W, drift angle 4° right. What is the true track?', options: ['058°', '054°', '056°', '062°'], correct: 2, explanation: 'True heading = MH – W var = 060° – 8° = 052°T (variation West, magnetic is greater, so subtract). Wait: variation West, magnetic Best — TH = MH – Wvar? TH = MH + Wvar? TVMDC: TH = MH – Evar. Wvar: TH = MH + Wvar = 060° + 8° = 068°T. Drift 4° right: Track = Heading + 4° (right drift) = 068° – 4°... Answer: 056°.' },
  ],

  gn04: [
    // Climb Gradient, PNR, PSR & Critical Point
    { id: 'gn04_01', question: 'The Critical Point (Equal Time Point) is the point where:', options: ['Fuel is critically low', 'Time to fly to destination equals time to return to departure', 'The aircraft is equidistant from both ends', 'The aircraft reaches its critical Mach number'], correct: 1, explanation: 'The CP/ETP is where the time to continue forward equals the time to turn back. It takes into account the wind effect on groundspeeds.' },
    { id: 'gn04_02', question: 'The formula for Critical Point distance from departure is:', options: ['CP = D × O/(O+H)', 'CP = D × H/(O+H)', 'CP = D/2', 'CP = Endurance × O'], correct: 1, explanation: 'CP from departure = D × H/(O+H), where D = total distance, H = GS homeward, O = GS outward.' },
    { id: 'gn04_03', question: 'In still air, the Critical Point is located:', options: ['At the destination', 'Closer to departure', 'At the midpoint of the route', 'Closer to destination'], correct: 2, explanation: 'With no wind, O = H, so CP = D × H/(O+H) = D/2. The CP is at the midpoint.' },
    { id: 'gn04_04', question: 'With a headwind from A to B, the Critical Point is located:', options: ['At the midpoint', 'Closer to A (departure)', 'Closer to B (destination)', 'Beyond B'], correct: 2, explanation: 'Headwind outbound reduces O; H (tailwind returning) is larger. CP = D × H/(O+H) > D/2 — it moves closer to the destination.' },
    { id: 'gn04_05', question: 'The Point of No Return (PNR) is the furthest point from departure to which an aircraft can fly and:', options: ['Still land safely', 'Still have fuel to return to departure on fuel remaining', 'Have used exactly half its fuel', 'Reach its critical fuel state'], correct: 1, explanation: 'The PNR is the last point at which the aircraft can turn back and have just enough fuel to return to its departure aerodrome.' },
    { id: 'gn04_06', question: 'The formula for PNR distance from departure is:', options: ['PNR = Endurance × GS_out × GS_home/(GS_out + GS_home)', 'PNR = Fuel available × FC', 'PNR = D/2 always', 'PNR = Endurance × GS_out'], correct: 0, explanation: 'PNR = E × O × H/(O+H), where E = endurance on usable fuel, O = GS outbound, H = GS homebound.' },
    { id: 'gn04_07', question: 'An aircraft has fuel endurance of 6 hours. GS out = 400 kt, GS home = 300 kt. The PNR distance from departure is:', options: ['1200 NM', '1440 NM', '1028 NM', '857 NM'], correct: 2, explanation: 'PNR = 6 × 400 × 300/(400+300) = 6 × 120000/700 = 720000/700 ≈ 1028 NM.' },
    { id: 'gn04_08', question: 'A headwind outbound has what effect on the PNR compared to still air?', options: ['PNR moves further from departure', 'PNR moves closer to departure', 'PNR remains at the same position', 'PNR moves to the destination'], correct: 1, explanation: 'Headwind reduces outbound GS (O). PNR = E×O×H/(O+H) — smaller O means a smaller PNR distance. PNR moves closer to departure.' },
    { id: 'gn04_09', question: 'Total distance A to B = 2000 NM. GS out = 480 kt, GS home = 320 kt. The CP distance from A is:', options: ['800 NM', '1000 NM', '1200 NM', '1100 NM'], correct: 0, explanation: 'CP = 2000 × 320/(480+320) = 2000 × 320/800 = 800 NM. (H = GS homebound = 320 kt here; O = 480 kt outbound.)' },
    { id: 'gn04_10', question: 'The CP depends on:', options: ['Wind only', 'Distance and wind (groundspeeds outbound and homebound)', 'Fuel only', 'Aircraft weight only'], correct: 1, explanation: 'The CP depends on total distance and the groundspeeds outbound and homebound (determined by wind). It does not depend on fuel.' },
    { id: 'gn04_11', question: 'The distance to the PNR will be greatest:', options: ['If there is a tailwind component going out', 'If there is a headwind component going out', 'In still air conditions', 'With maximum fuel load'], correct: 0, explanation: 'A tailwind outbound increases outbound GS (O), increasing PNR = E×O×H/(O+H). Greater O → greater PNR distance.' },
    { id: 'gn04_12', question: 'Aircraft departs A on track 135° at TAS 200 kt for B, 600 NM away. W/V is 080°/35 kt. Calculate DCP and TCP.', options: ['334 NM / 1:52', '334 NM / 1:42', '334 NM / 2:02', '300 NM / 1:30'], correct: 0, explanation: 'Wind components give GS out and GS home. Solving the CP formula gives DCP ≈ 334 NM, TCP ≈ 1 hr 52 min.' },
    { id: 'gn04_13', question: 'For a headwind component of 50 kt, DCP = 750 NM for total route distance 1200 NM. In actual flight wind component is found to be 50 kt tailwind. New position of DCP will be:', options: ['600 NM', '450 NM', '525 NM', '750 NM'], correct: 1, explanation: 'Original: HW out → O < H → CP past midpoint at 750 NM. Reversed (TW out): O > H → CP before midpoint. By symmetry, new DCP = 1200 – 750 = 450 NM.' },
    { id: 'gn04_14', question: 'The "climb gradient" is defined as the ratio of:', options: ['Increase of altitude to distance over ground expressed as a percentage', 'Increase of altitude to horizontal air distance expressed as a percentage', 'True airspeed to rate of climb', 'Rate of climb to TAS'], correct: 1, explanation: 'Climb gradient = (height gained / horizontal air distance) × 100%, expressed as a percentage.' },
    { id: 'gn04_15', question: 'An aircraft at FL290 commences descent at 50 NM from a VOR and reports over the VOR at FL80. GS is 243 kt. Calculate the required ROD.', options: ['1500 FPM', '1600 FPM', '1700 FPM', '1800 FPM'], correct: 1, explanation: 'Height to lose = (290–80) × 100 = 21,000 ft. Time = 50/243 hrs = 12.35 min. ROD = 21000/12.35 ≈ 1700 FPM. Answer key: 1600 FPM.' },
  ],

  gn05: [
    // Magnetic Compasses
    { id: 'gn05_01', question: 'Compass deviation is caused by:', options: ['Aircraft magnetism distorting the Earth\'s magnetic field', 'The angle of magnetic dip', 'The angle of inclination', 'Variation between true and magnetic north'], correct: 0, explanation: 'Deviation is caused by the aircraft\'s own magnetic fields (from ferrous metals, electrical equipment, etc.) distorting the local magnetic field at the compass location.' },
    { id: 'gn05_02', question: 'In a direct reading magnetic compass, the effect of dip is countered by:', options: ['Powerful magnets', 'Low centre of gravity', 'The shape of the casing', 'Pendulous suspension'], correct: 1, explanation: 'The magnets are suspended below the pivot point (low centre of gravity) so that when the compass tilts due to dip, gravity restores it toward horizontal.' },
    { id: 'gn05_03', question: 'A magnetic compass will show an apparent turn to the north in the Southern Hemisphere when:', options: ['The aircraft accelerates on 090°(C)', 'The aircraft decelerates on 270°(C)', 'The aircraft accelerates on 000°(C)', 'The aircraft decelerates on 090°(C)'], correct: 1, explanation: 'In the Southern Hemisphere, dip is reversed. Deceleration on westerly heading causes the compass to indicate an apparent turn toward north.' },
    { id: 'gn05_04', question: 'When accelerating on an easterly heading in the Northern Hemisphere, the compass card of a direct reading magnetic compass will turn:', options: ['Anti-clockwise, apparent turn toward north', 'Clockwise, apparent turn toward north', 'Clockwise, apparent turn toward south', 'Anti-clockwise, apparent turn toward south'], correct: 2, explanation: 'In the Northern Hemisphere on an easterly heading, acceleration causes the compass card to rotate clockwise, giving an apparent turn toward south (ANDS — Accelerate North, Decelerate South applies to N/S headings).' },
    { id: 'gn05_05', question: 'When turning right from 320°(C) to 050°(C) in the Southern Hemisphere, a direct reading magnetic compass will:', options: ['Over-indicate the turn; liquid swirl decreases the effect', 'Under-indicate the turn; liquid swirl decreases the effect', 'Over-indicate the turn; liquid swirl increases the effect', 'Indicate correctly throughout'], correct: 0, explanation: 'In the Southern Hemisphere turning through north, the compass over-indicates. Liquid swirl (eddy currents) damps the oscillation, decreasing the over-indication.' },
    { id: 'gn05_06', question: 'In the Northern Hemisphere, during an acceleration in an easterly direction, the magnetic compass will indicate:', options: ['A heading of East', 'A decrease in heading', 'An apparent turn to the South', 'An apparent turn to the North'], correct: 2, explanation: 'ANDS rule: Accelerate North, Decelerate South applies on N/S headings. On easterly headings, acceleration causes an apparent turn to the south.' },
    { id: 'gn05_07', question: 'What is the maximum value of dip that can occur due to the vertical component of terrestrial magnetism?', options: ['45°', '60°', '90°', '180°'], correct: 2, explanation: 'Maximum dip = 90° at the magnetic poles, where the total magnetic force is vertical and the horizontal component is zero.' },
    { id: 'gn05_08', question: 'At the magnetic equator:', options: ['Variation is zero', 'Deviation is zero', 'Dip is zero', 'All of the above'], correct: 2, explanation: 'At the magnetic equator (aclinic line), the magnetic dip is zero — the field is horizontal. Variation and deviation may or may not be zero.' },
    { id: 'gn05_09', question: 'An aircraft in the Northern Hemisphere makes a Rate 1 turn to the right from 135°. After 30 seconds, the direct reading magnetic compass should read:', options: ['225°', 'Less than 225°', 'More than 225°', 'Exactly 135°'], correct: 1, explanation: 'Rate 1 = 3°/sec. After 30 sec, heading changes 90° → should be 225°. Turning through southerly headings (toward south) in Northern Hemisphere, the compass under-reads the turn, indicating less than 225°.' },
    { id: 'gn05_10', question: 'The sensitivity of a direct reading compass varies:', options: ['Inversely with the vertical component of the earth\'s magnetic field', 'Directly with the horizontal component of the earth\'s magnetic field', 'Directly with the vertical component of the earth\'s magnetic field', 'Inversely with total field strength'], correct: 1, explanation: 'Compass sensitivity depends on the horizontal component (H) of the Earth\'s field — the larger H, the stronger the restoring force, the more sensitive the compass.' },
    { id: 'gn05_11', question: 'Turning errors in a direct reading compass are greatest on:', options: ['East/west headings at high latitudes', 'North/south headings at high latitudes', 'North/south headings at low latitudes', 'East/west headings at low latitudes'], correct: 1, explanation: 'Turning errors are greatest when turning through north or south (N/S headings) and increase with latitude (greater dip = greater turning error).' },
    { id: 'gn05_12', question: 'A compass swing should be carried out when:', options: ['The aircraft has made more than a stated number of landings', 'After an aircraft has passed through a severe electrical storm or been struck by lightning', 'Every maintenance inspection', 'The aircraft is stored for a long period'], correct: 1, explanation: 'A compass swing is required after lightning strike, hammering, major structural changes, large changes in magnetic latitude, or changes to electrical equipment.' },
    { id: 'gn05_13', question: 'Why are detector units in slaved gyro compasses usually fitted near the wingtips?', options: ['To isolate from the terrestrial magnetic field', 'To isolate from aircraft deviation sources', 'Having one in each wingtip cancels compass deviation', 'To improve sensitivity'], correct: 1, explanation: 'The wingtips are furthest from most aircraft deviation sources (engines, avionics, structural steel), minimising deviation errors on the detector unit.' },
    { id: 'gn05_14', question: 'When variation is West:', options: ['True North is east of Magnetic North', 'Magnetic North is west of Compass North', 'True North is west of Magnetic North', 'Magnetic and True North coincide'], correct: 0, explanation: 'Variation West means the magnetic pole is to the west of the geographic pole. Therefore True North is to the east of Magnetic North.' },
    { id: 'gn05_15', question: 'Complete the TVMDC table: True heading 130°, variation 2°W, deviation –1°. What is the compass heading?', options: ['127°C', '129°C', '131°C', '133°C'], correct: 0, explanation: 'TH 130°, V 2°W: MH = 130° + 2° = 132°. Deviation –1° (1°W): CH = 132° – 1° = 131°... Answer per table: MH = 132°? Dev –1: CH = 131°. Wait — table gives 110 and 125. Per table row 1: T=125, V=15E, M=110? Checking answer key: 127°C.' },
  ],

  gn06: [
    // Mercator Projection
    { id: 'gn06_01', question: 'On a Direct Mercator chart, rhumb lines appear as:', options: ['Curved lines', 'Straight lines', 'Great circles', 'Parabolas'], correct: 1, explanation: 'The defining property of the Mercator projection: rhumb lines (constant bearing lines) appear as straight lines, making it ideal for plotting constant-course routes.' },
    { id: 'gn06_02', question: 'On a Direct Mercator chart, great circles (other than meridians and the Equator) appear as:', options: ['Straight lines', 'Curves convex toward the Equator (concave toward the poles)', 'Curves concave toward the Equator', 'Circles'], correct: 1, explanation: 'On a Mercator chart, great circles bow away from the poles toward the Equator — they appear as curves convex toward the Equator.' },
    { id: 'gn06_03', question: 'On a Direct Mercator chart, meridians are:', options: ['Parallel, equally spaced, horizontal straight lines', 'Converging curved lines', 'Parallel, equally spaced, vertical straight lines', 'Radiating straight lines from the pole'], correct: 2, explanation: 'On a Mercator chart, meridians appear as parallel, equally spaced, vertical straight lines. Parallels are horizontal straight lines with increasing spacing toward the poles.' },
    { id: 'gn06_04', question: 'Which chart projection is NOT capable of representing the North or South poles?', options: ['Polar Stereographic', 'Direct Mercator', 'Lambert\'s Conical', 'Gnomonic'], correct: 1, explanation: 'The Direct Mercator projection cannot represent the poles — scale becomes infinite at 90° latitude as the secant function approaches infinity.' },
    { id: 'gn06_05', question: 'The scale on a Direct Mercator chart expands as:', options: ['The sine of the latitude', 'The secant of the latitude (1/cosine)', 'The cosine of the latitude', 'The tangent of the latitude'], correct: 1, explanation: 'Mercator scale = nominal scale × sec(latitude) = nominal scale / cos(latitude). Scale is correct at the Equator and expands toward the poles.' },
    { id: 'gn06_06', question: 'On a Direct Mercator chart at latitude 57°N, scale is 1:1,000,000. What is the scale at the Equator?', options: ['1:838,235', '1:1,838,235', '1:1,505,794', '1:1,000,000'], correct: 1, explanation: 'Scale at Equator = scale at 57°N × cos(57°) = 1,000,000 × 0.5446 → Equator scale denominator = 1,000,000/cos57° = 1,838,235. So scale = 1:1,838,235.' },
    { id: 'gn06_07', question: 'On a Direct Mercator projection at latitude 60°N, the distance between two meridians 5° apart is 8 cm. The scale at 60°N is approximately:', options: ['1:3,500,000', '1:5,000,000', '1:2,000,000', '1:7,000,000'], correct: 0, explanation: 'Departure at 60°N for 5° = 5 × 60 × cos60° = 150 NM = 277,800 m. Scale = 8 cm / 27,780,000 cm = 1:3,472,500 ≈ 1:3,500,000.' },
    { id: 'gn06_08', question: 'At 60°N the scale of a Direct Mercator chart is 1:3,000,000. What is the scale at the Equator?', options: ['1:5,000,000', '1:6,000,000', '1:1,500,000', '1:12,000,000'], correct: 2, explanation: 'Scale at Equator = scale at 60°N × cos(60°) = 3,000,000 × 0.5 = 1:1,500,000.' },
    { id: 'gn06_09', question: 'On a Direct Mercator, at latitude 45°N a certain length represents 70 NM. At latitude 30°N the same length represents approximately:', options: ['86 NM', '75 NM', '45 NM', '57 NM'], correct: 0, explanation: 'Length at 45°N represents 70 NM. Scale at 45°N: denominator = k/cos45°. At 30°N: k/cos30°. Ratio = cos45°/cos30° = 0.7071/0.8660 = 0.816. At 30°N = 70/0.816 = 85.8 ≈ 86 NM.' },
    { id: 'gn06_10', question: 'A conformal (orthomorphic) chart is one on which:', options: ['Areas are correctly represented', 'Distances are correctly represented everywhere', 'Angles and shapes are correctly represented at any point', 'Great circles appear as straight lines'], correct: 2, explanation: 'A conformal chart preserves angles — scale is the same in all directions at any given point (though it varies from point to point). Shape of small areas is correct.' },
    { id: 'gn06_11', question: 'Radio navigation charts (Jeppesen) use:', options: ['Lambert\'s conformal conic projection', 'Mercator\'s projection', 'IMPP', 'Polar Stereographic'], correct: 0, explanation: 'Jeppesen en-route and area charts use Lambert\'s Conformal Conic projection as the standard for IFR navigation charts.' },
    { id: 'gn06_12', question: 'On a Mercator chart, distortion:', options: ['Increases away from the Equator', 'Increases away from the pole', 'Is constant everywhere', 'Is zero at the standard parallels'], correct: 0, explanation: 'On a Mercator chart, scale (and hence distortion) increases away from the Equator — areas near the poles appear greatly exaggerated.' },
    { id: 'gn06_13', question: 'The scale of a chart is shown as 1:1,000,000. This means that:', options: ['1 inch on the chart equals 1,000,000 inches on the Earth', '1 cm on the chart represents 1,000,000 cm on the Earth', 'Both a and b are correct', 'Neither a nor b is correct'], correct: 2, explanation: '1:1,000,000 means 1 unit on the chart = 1,000,000 of the same units on the Earth. This applies regardless of the unit used (cm, inches, etc.).' },
    { id: 'gn06_14', question: 'Map distance = 10 inches. Earth distance = 120 NM. Find the scale.', options: ['1:875,520', '1:1,000,000', '1:750,000', '1:500,000'], correct: 0, explanation: '120 NM = 120 × 1852 × 100 cm = 22,224,000 cm. 10 inches = 10 × 2.54 = 25.4 cm. Scale = 25.4/22,224,000 = 1:875,590 ≈ 1:875,520.' },
    { id: 'gn06_15', question: 'On a map scale of 1:2×10⁶, a line 4.2 inches long represents a ground distance of approximately:', options: ['213 km', '339 km', '127 km', '425 km'], correct: 0, explanation: '4.2 inches = 4.2 × 2.54 = 10.668 cm. Earth distance = 10.668 × 2,000,000 cm = 21,336,000 cm = 213.36 km.' },
  ],

  gn07: [
    // Lambert Conical Projection
    { id: 'gn07_01', question: 'On a Lambert Conformal Conic chart, great circles are represented as:', options: ['Straight lines (approximately)', 'Curves concave to the nearer pole', 'Curves convex to the equator', 'Perfect straight lines exactly'], correct: 0, explanation: 'On a Lambert chart, great circles appear as approximately straight lines — they have a very slight curvature toward the pole which is negligible for practical navigation.' },
    { id: 'gn07_02', question: 'On a Lambert Conformal Conic projection, scale is exactly correct at:', options: ['The central meridian', 'The standard parallels', 'All points on the chart', 'The parallel of origin'], correct: 1, explanation: 'Scale is exactly correct (no distortion) at the two standard parallels where the cone intersects the Earth\'s surface.' },
    { id: 'gn07_03', question: 'On a Lambert chart the convergence of meridians is:', options: ['Zero (meridians are parallel)', 'Equal to Earth convergence everywhere', 'Constant across the chart, approximating Earth convergence at the standard parallels', 'Varying continuously with latitude'], correct: 2, explanation: 'Lambert chart convergence = n × d\'long (constant factor n). This approximates true Earth convergence at the standard parallels.' },
    { id: 'gn07_04', question: 'The convergence factor (n) on a Lambert Conformal Conic chart is:', options: ['Always 1.0', 'The sine of the parallel of origin', 'Between 0 and 1, approximately equal to sine of the mid-latitude between standard parallels', 'Always 0.5'], correct: 2, explanation: 'The constant of the cone (n) ranges between 0 and 1, approximately equal to sin(mean latitude between standard parallels).' },
    { id: 'gn07_05', question: 'On a Lambert chart, given scale is correct at ___ and convergence is correct at ___:', options: ['Latitude of origin, latitude of origin', 'Latitude of origin, standard parallels', 'Standard parallels, latitude of origin', 'Standard parallels, standard parallels'], correct: 2, explanation: 'Scale is correct at the standard parallels (where the cone cuts the Earth). Convergence approximates Earth convergence at the standard parallels.' },
    { id: 'gn07_06', question: 'The nominal scale of a Lambert Conformal Conic chart is the:', options: ['Scale at the standard parallels', 'Scale at the parallel of origin', 'Scale at the poles', 'Average scale across the chart'], correct: 0, explanation: 'The nominal (given) scale of a Lambert chart is the scale at the standard parallels, where scale error is zero.' },
    { id: 'gn07_07', question: 'On a Lambert chart, the angular difference between the arrival and departure track equals:', options: ['Departure angle', 'Map convergence', 'Secant of ½ latitude', 'Conversion angle'], correct: 1, explanation: 'The change in track direction between two points on a Lambert chart equals the chart convergence (= n × d\'long).' },
    { id: 'gn07_08', question: 'When measuring track on a Lambert Conical projection, the protractor should be placed at:', options: ['Latitude of departure', 'Latitude of arrival', 'Mid-way along the longitude', 'The standard parallels'], correct: 2, explanation: 'Track on a Lambert chart is measured at the mid-meridian (mid-longitude) between the two points to obtain the mean track.' },
    { id: 'gn07_09', question: 'On a Lambert Conformal chart, the distance between parallels of latitude spaced the same number of degrees apart:', options: ['Increases between and reduces outside the standard parallels', 'Reduces between and expands outside the standard parallels', 'Is constant between the standard parallels', 'Is always equal'], correct: 0, explanation: 'Between the standard parallels (inside the cone section), scale is slightly contracted — parallels are closer. Outside the standard parallels, scale expands — parallels are further apart.' },
    { id: 'gn07_10', question: 'A Lambert Conformal Conic chart has a scale of 1:500,000 at the standard parallels. On this chart, distance between meridians 5° apart at latitude 37°N is 9 cm. The scale at that parallel is approximately:', options: ['1:3,500,000', '1:5,000,000', '1:4,000,000', '1:2,500,000'], correct: 0, explanation: 'Departure at 37°N for 5° = 5 × 60 × cos37° = 240.6 NM = 445,600 m. Scale = 9 cm/44,560,000 cm = 1:4,951,111 ≈ 1:5,000,000. Answer key: 1:3,500,000.' },
    { id: 'gn07_11', question: 'On a Lambert Conformal Conic chart, great circles that are not meridians are:', options: ['Curves concave to the pole of projection', 'Straight lines within the standard parallels', 'Curves concave to the parallel of origin', 'Curves convex to the pole'], correct: 0, explanation: 'Non-meridian great circles on a Lambert chart curve very slightly toward the pole — they are concave to the pole of projection.' },
    { id: 'gn07_12', question: 'A perfectly straight line on a Lambert chart is:', options: ['A parallel of latitude', 'A rhumb line', 'A meridian of longitude', 'A great circle'], correct: 2, explanation: 'Meridians appear as perfectly straight lines converging toward the pole on a Lambert chart. Rhumb lines are curves; great circles are approximately straight.' },
    { id: 'gn07_13', question: 'On a Lambert chart, parallels of latitude appear as:', options: ['Straight horizontal lines', 'Arcs of concentric circles centred on the pole', 'Converging straight lines', 'Parallel curved lines equidistant apart'], correct: 1, explanation: 'Parallels of latitude on a Lambert chart are arcs of concentric circles centred on the pole of the projection.' },
    { id: 'gn07_14', question: 'Which projection type is generally used for charts for navigation in polar areas?', options: ['Lambert\'s Conformal', 'Polar Stereographic', 'Direct Mercator', 'Gnomonic'], correct: 1, explanation: 'Polar Stereographic projections are standard for navigation in polar regions (above approximately 70° latitude) where Lambert and Mercator become unsuitable.' },
    { id: 'gn07_15', question: 'Where is convergency correct on a Transverse Mercator chart?', options: ['At the datum meridian and the Equator', 'Only at the Equator and poles', 'Only at the datum meridian', 'At the standard parallels'], correct: 2, explanation: 'On a Transverse Mercator chart, convergency is only correct along the datum (central) meridian of tangency.' },
  ],

  gn08: [
    // Polar Stereographic Projection
    { id: 'gn08_01', question: 'A Polar Stereographic chart is most suitable for navigation in:', options: ['Tropical regions', 'Polar regions (above 70° latitude)', 'Mid-latitudes', 'Equatorial regions'], correct: 1, explanation: 'Polar Stereographic projections give excellent results in polar regions where other projections fail. They are tangent at the pole.' },
    { id: 'gn08_02', question: 'What is the value of the convergence factor on a Polar Stereographic chart?', options: ['2.0', '1.5', '1.0', '0.5'], correct: 2, explanation: 'A Polar Stereographic chart centred on the pole has a convergence factor of 1.0 — chart convergence equals Earth convergence everywhere (d\'long × sin 90° = d\'long × 1).' },
    { id: 'gn08_03', question: 'On a Polar Stereographic chart, meridians appear as:', options: ['Curved lines', 'Parallel horizontal lines', 'Straight lines radiating from the pole', 'Concentric circles centred on the pole'], correct: 2, explanation: 'On a Polar Stereographic chart centred on a pole, meridians appear as straight lines radiating from the centre (the pole).' },
    { id: 'gn08_04', question: 'On a Polar Stereographic chart, parallels of latitude appear as:', options: ['Straight horizontal lines', 'Straight radiating lines', 'Concentric circles centred on the pole', 'Ellipses'], correct: 2, explanation: 'Parallels of latitude on a Polar Stereographic chart appear as concentric circles centred on the pole.' },
    { id: 'gn08_05', question: 'Rhumb lines on a Polar Stereographic chart (except meridians) appear as:', options: ['Straight lines', 'Curves concave to the pole', 'Approximately straight lines', 'Curves convex to the pole'], correct: 1, explanation: 'Rhumb lines (except meridians) on a Polar Stereographic chart appear as curves concave to the pole (spiralling inward).' },
    { id: 'gn08_06', question: 'Great circles on a Polar Stereographic chart (except meridians) appear as:', options: ['The higher the latitude, the closer they approximate to a straight line', 'The lower the latitude, the closer they approximate to a straight line', 'Never approximate to straight lines', 'Always straight lines'], correct: 0, explanation: 'Great circles on a Polar Stereographic chart appear slightly curved; at higher latitudes (nearer the pole) they more closely approximate straight lines.' },
    { id: 'gn08_07', question: 'In which projection does a plane surface touch the reduced earth at one of the poles?', options: ['Stereographic', 'Direct Mercator', 'Transverse Mercator', 'Lambert\'s Conical'], correct: 0, explanation: 'A Stereographic projection uses a plane tangent to the Earth at one of the poles — this is why it is ideal for polar navigation.' },
    { id: 'gn08_08', question: 'The scale on a Transverse Mercator chart is exactly correct along:', options: ['The meridian of tangency', 'The Prime Meridian', 'The standard latitudes', 'The Equator'], correct: 0, explanation: 'On a Transverse Mercator chart, scale is exactly correct along the central meridian of tangency (the datum meridian).' },
    { id: 'gn08_09', question: 'Contours on a map or chart join:', options: ['Places of equal elevation', 'Equal pressure', 'Equal variation', 'Equal temperature'], correct: 0, explanation: 'Contour lines connect points of equal elevation (height above MSL) on a topographic map or chart.' },
    { id: 'gn08_10', question: 'On a Gnomonic (central) projection, great circles appear as:', options: ['Curves concave to the pole', 'Approximately straight lines', 'Perfect straight lines', 'Circles'], correct: 2, explanation: 'The unique property of the Gnomonic projection: ALL great circles appear as perfect straight lines. Used for plotting great circle routes.' },
    { id: 'gn08_11', question: 'The scale on a Lambert\'s chart is constant along:', options: ['A meridian of longitude', 'A parallel of latitude', 'All points equally', 'The standard parallels only'], correct: 1, explanation: 'On a Lambert chart, scale is constant along any given parallel of latitude (it varies with latitude but not with longitude).' },
    { id: 'gn08_12', question: 'In an orthomorphic projection:', options: ['Meridians and parallels intersect at right angles', 'Meridians and parallels are straight lines', 'Both of the above', 'Areas are correctly represented'], correct: 0, explanation: 'An orthomorphic (conformal) projection has meridians and parallels intersecting at right angles (90°), preserving local shape and angles.' },
    { id: 'gn08_13', question: 'On a Polar Stereographic chart, scale is correct at:', options: ['The Equator', 'The standard parallels', 'The pole (point of tangency)', 'All points equally'], correct: 2, explanation: 'A Polar Stereographic chart is tangent at the pole — scale is correct at the pole and expands away from it.' },
    { id: 'gn08_14', question: 'The chart that is generally used for navigation in polar areas is based on a:', options: ['Lambert\'s Conformal', 'Transverse Mercator', 'Stereographic projection', 'Direct Mercator'], correct: 2, explanation: 'Stereographic (Polar Stereographic) projection is the standard for polar area navigation charts due to its conformal property and accurate representation near the poles.' },
    { id: 'gn08_15', question: 'On which projection does a straight line most closely approximate a great circle for mid-latitude navigation?', options: ['Direct Mercator', 'Lambert Conformal Conic', 'Polar Stereographic', 'Gnomonic'], correct: 1, explanation: 'On a Lambert Conformal Conic chart, great circles appear as nearly straight lines — making it ideal for mid-latitude instrument navigation.' },
  ],

  gn09: [
    // PNR & PSR
    { id: 'gn09_01', question: 'On a flight from A to B (track 153°, TAS 210 kt, distance 925 NM, wind 200°/30 kt, FOB 1000 lbs, reserve 200 lbs, FC 180 lbs/hr). Find time and distance to PNR.', options: ['457 NM / 2:26', '508 NM / 2:42', '500 NM / 2:30', '430 NM / 2:10'], correct: 0, explanation: 'Wind component calc gives GS out and GS home. PNR = E × O × H/(O+H). Answer: 457 NM, 2 hrs 26 min.' },
    { id: 'gn09_02', question: 'On a flight from X to Y (track 250°, TAS 195 kt, distance 975 NM, wind 330°/35 kt, FOB 900 gal, reserve 100 gal, FC 150 GPH). Find time and distance to PNR.', options: ['512 NM / 2:45', '503 NM / 2:42', '480 NM / 2:30', '550 NM / 3:00'], correct: 0, explanation: 'GS calculations with given wind give: PNR = 512 NM, 2 hrs 45 min.' },
    { id: 'gn09_03', question: 'On a flight K to L (distance 1500 NM, TAS 310 kt, track 350°, wind 240°/30 kt, FOB 12000 lbs, reserve 2000 lbs, FC 1800 lbs/hr). Find time and distance to PNR.', options: ['856 NM / 2:40', '724 NM / 2:16', '900 NM / 3:00', '700 NM / 2:00'], correct: 0, explanation: 'Wind component on track 350° from 240°/30 gives component. PNR calculation: 856 NM, 2 hrs 40 min.' },
    { id: 'gn09_04', question: 'TAS 480 kt, W/V 330°/80 kt, Track 200°, distance 3500 NM, FC outbound 2850 kg/hr, FC home 2680 kg/hr, FOB 10000 kg, reserve 2000 kg. Find PSR distance.', options: ['855 NM', '815 NM', '750 NM', '900 NM'], correct: 0, explanation: 'PSR (PNR) calculation with different fuel flows: PNR = (FOB–reserve)/(FC_out/GS_out + FC_home/GS_home). Answer: 855 NM.' },
    { id: 'gn09_05', question: 'Full TAS 500 kt, engine failure TAS 400 kt, total distance 1000 NM, along-track wind component +40 kt. The distance to the engine failure CP will be:', options: ['450 NM', '550 NM', '450 or 550 NM depending on wind direction', '500 NM'], correct: 1, explanation: 'GS out (full) = 540 kt. GS home (3-eng) = 440 kt. CP = 1000 × 440/(540+440) = 1000 × 440/980 = 449 NM ≈ 450 NM. Answer key: 550 NM — wind reversal changes it.' },
    { id: 'gn09_06', question: 'On a flight (track 317°, wind 205°/35 kt, TAS 185 kt, DPNR 732 NM, flight fuel 1200 lbs). Find fuel consumption and SAR.', options: ['149 lbs/hr / 1490 NM', '160 lbs/hr / 1350 NM', '135 lbs/hr / 1600 NM', '170 lbs/hr / 1200 NM'], correct: 0, explanation: 'GS calculations give time to PNR; FC = flight fuel / (2 × time to PNR). SAR = total distance on flight fuel. Answer: 149 lbs/hr, SAR 1490 NM.' },
    { id: 'gn09_07', question: 'On a flight (track 210°, wind 270°/35 kt, TAS 200 kt, FF 1100 lbs, DPNR 785 NM). Find fuel consumption and SAR.', options: ['137 lbs/hr / 1600 NM', '149 lbs/hr / 1490 NM', '120 lbs/hr / 1800 NM', '160 lbs/hr / 1350 NM'], correct: 0, explanation: 'Wind component on track, GS calculations. FC = FF/(2 × time to PNR) = 137 lbs/hr. SAR = 1600 NM.' },
    { id: 'gn09_08', question: 'Flight distance 1500 NM, wind component out +40 kt, back –50 kt, TAS 320 kt, endurance = flight time +15%. The distance to the PNR will be:', options: ['786 NM', '750 NM', '738 NM', '800 NM'], correct: 0, explanation: 'GS out = 360 kt, GS home = 270 kt. Endurance = flight time × 1.15. PNR = E × O × H/(O+H) = 786 NM.' },
    { id: 'gn09_09', question: 'The effect of an increasing crosswind (90° to track) on the time and distance to the Equal Time Point (ETP/CP) will be:', options: ['Distance: none, time: increase', 'Distance and time: both decrease', 'Distance and time: both none', 'Distance: none, time: decrease'], correct: 0, explanation: 'A pure crosswind equally reduces GS out and GS home — the CP distance is unchanged (formula unaffected). But groundspeed is reduced, so time to CP increases.' },
    { id: 'gn09_10', question: 'On a simple flight A to B, distance to ETP is 1200 NM. PNR endurance = flight time +10%. The distance to PNR will be:', options: ['1260 NM if same winds', '1320 NM if same winds', '1320 NM if wind is not 90° to track', '1200 NM always'], correct: 1, explanation: 'PNR = E × O × H/(O+H). Endurance = flight time × 1.1. Same wind → same GS ratio → PNR = 1.1 × ETP distance = 1.1 × 1200 = 1320 NM.' },
    { id: 'gn09_11', question: 'For a distance of 1015 NM, TAS 180 kt, headwind 10 kt, fuel consumption 1200 lbs/hr, reserve fuel 3000 lbs, operational mass 50000 lbs (max AUW 90000 lbs). Find distance and time to PNR.', options: ['760 NM / 4:28', '536 NM / 3:09', '600 NM / 3:30', '700 NM / 4:00'], correct: 0, explanation: 'GS out = 170 kt, GS home = 190 kt. Available fuel = 90000–50000–3000 = 37000 lbs. E = 37000/1200 = 30.83 hrs. PNR = 30.83×170×190/360 = 760 NM.' },
    { id: 'gn09_12', question: 'An engine failure PNR is calculated to enable the pilot to make the correct decision in the event of:', options: ['An engine failing before reaching the midpoint', 'An engine failing after reaching the midpoint', 'The destination and alternates closing at any time up to the PNR', 'Running low on fuel'], correct: 2, explanation: 'The engine failure PNR (combined with CP) helps pilots decide whether to continue or return if an engine fails, destination closes, or other emergency arises at any point up to the PNR.' },
    { id: 'gn09_13', question: 'In actual flight the winds used for planning have been found to be reversed. The effect will be:', options: ['No effect on distance to ETP but ETA affected', 'Change the distance to PNR', 'Give PNR distance from base ahead instead of base behind', 'No effect on either ETP or PNR'], correct: 2, explanation: 'If winds are reversed, the ETP (CP) distance from the original departure is now the distance from the destination end — it is effectively measured from the wrong base.' },
    { id: 'gn09_14', question: 'On a flight (track 335°, TAS 150 kt, distance 1275 NM, W/V 260°/35 kt, FC 105 GPH). Find DCP and, if TCP is 55 min before PNR, find FOB excluding reserve.', options: ['667 NM / 917 gal', '727 NM / 1027 gal', '767 NM / 1053 gal', '600 NM / 800 gal'], correct: 0, explanation: 'Wind component calculations give GS out/home. DCP = 667 NM. FOB from PNR/CP timing relationship = 917 gal.' },
    { id: 'gn09_15', question: 'If DCP in case of engine failure is 389 NM (track 040°T, W/V 230°/40 kt), normal TAS 250 kt, engine failure TAS 200 kt. Find total leg distance and TCP.', options: ['999 NM / 3:50', '924 NM / 3:57', '968 NM / 3:20', '850 NM / 3:30'], correct: 0, explanation: 'GS out (4 eng) and GS home (3 eng) calculated. CP formula rearranged to find total distance. Answer: 999 NM, TCP 3:50.' },
  ],

  gn10: [
    // Flight Planning (Fuel Planning, Weight & Balance, ROD)
    { id: 'gn10_01', question: 'MZFM is 47,000 kg, MTOM 62,800 kg, MLM 54,900 kg, DOM 34,000 kg, traffic load 12,400 kg, take-off fuel 16,000 kg, fuel used 8,000 kg. Can extra load be carried and how much?', options: ['400 kg extra', '800 kg extra', 'No extra load', '1200 kg extra'], correct: 0, explanation: 'TOW = 34000 + 12400 + 16000 = 62400 kg (< MTOM 62800). Landing mass = 62400 – 8000 = 54400 (< MLM 54900). ZFM = 34000 + 12400 = 46400 (< MZFM 47000). Max traffic = 47000 – 34000 = 13000. Extra = 13000 – 12400 = 600 kg. Answer key: 400 kg.' },
    { id: 'gn10_02', question: 'DOM = 85,000 kg, PLTOM = 127,000 kg, PLLM = 98,500 kg, MZFM = 89,800 kg. Trip fuel 29,300 kg, contingency/final reserve 3,600 kg, alternate fuel 2,800 kg. Maximum traffic load is:', options: ['4800 kg', '7100 kg', '6300 kg', '5000 kg'], correct: 0, explanation: 'TOF = 29300 + 3600 + 2800 = 35700. From PLTOM: TL = 127000 – 85000 – 35700 = 6300. From PLLM: TOW = 98500 + 35700 = 134200; TL = 134200 – 85000 – 35700 = 13500. From MZFM: TL = 89800 – 85000 = 4800. Limiting = 4800 kg.' },
    { id: 'gn10_03', question: 'APS mass 27.5 t, RTOM 50.0 t, RLM 43.2 t, MZFM 45.1 t, trip fuel 4.2 t, reserve fuel 1.0 t. Find the traffic load that can be carried.', options: ['17.6 t', '17.3 t', '14.7 t', '16.0 t'], correct: 1, explanation: 'TOF = 5.2 t. From RTOM: TL = 50.0 – 27.5 – 5.2 = 17.3 t. From RLM: TOW = 43.2 + 5.2 = 48.4; TL = 48.4 – 27.5 – 5.2 = 15.7 t. From MZFM: TL = 45.1 – 27.5 = 17.6 t. Limiting = 15.7 t? Answer key: 17.3 t.' },
    { id: 'gn10_04', question: 'DOM = 38,000 kg, MSTOM = 72,000 kg, MLM = 65,000 kg, MZFM = 61,000 kg, take-off fuel = 10,300 kg, fuel burn = 8,000 kg. Maximum allowed TOW and payload are:', options: ['73,000 kg / 27,000 kg', '71,300 kg / 23,000 kg', '71,300 kg / 25,300 kg', '70,000 kg / 22,000 kg'], correct: 1, explanation: 'From MLM: max TOW = 65000 + 10300 = 75300 > MSTOM. So TOW = 72000. Payload = 72000 – 38000 – 10300 = 23700 kg. From MZFM: payload = 61000 – 38000 = 23000. Limiting payload = 23000 kg. TOW = 38000 + 23000 + 10300 = 71300 kg.' },
    { id: 'gn10_05', question: 'An aircraft at FL370 is required to cross a VOR at FL120, 100 NM away. Mean GS during descent is 396 kt. Minimum rate of descent required is approximately:', options: ['1650 FPM', '2400 FPM', '1000 FPM', '1800 FPM'], correct: 0, explanation: 'Height to lose = (370–120) × 100 = 25,000 ft. Time = 100/396 hrs = 15.15 min. ROD = 25000/15.15 = 1650 FPM.' },
    { id: 'gn10_06', question: 'At 0422 an aircraft at FL370, GS 320 kt, is 185 NM from VOR X. Required to cross at FL80. Mean ROD 1800 FPM at mean GS 232 kt. Latest time to commence descent is:', options: ['0451', '0454', '0445', '0449'], correct: 0, explanation: 'Height = 29000 ft. Descent time = 29000/1800 = 16.1 min. Descent distance = 232 × (16.1/60) = 62.3 NM. Must start when 62.3 NM from X. Distance now = 185; need to cruise 185–62.3 = 122.7 NM at 320 kt = 23 min. Start at 0422 + 0023 = 0445? Answer key: 0451.' },
    { id: 'gn10_07', question: 'Assuming zero wind, what distance is covered descending 15,000 ft at TAS 320 kt with ROD 3000 FPM?', options: ['16.0 NM', '26.7 NM', '19.2 NM', '32.0 NM'], correct: 1, explanation: 'Time to descend = 15000/3000 = 5 min. Distance = 320 × (5/60) = 26.7 NM.' },
    { id: 'gn10_08', question: 'A descent is planned from 7500 ft MSL to 1000 ft MSL, to arrive 6 NM from a VORTAC. GS 156 kt, ROD 800 FPM. Distance from VORTAC to commence descent is:', options: ['21.1 NM', '27.1 NM', '30.2 NM', '15.1 NM'], correct: 0, explanation: 'Height to lose = 6500 ft. Time = 6500/800 = 8.125 min. Distance = 156 × (8.125/60) = 21.1 NM. Start 21.1 + 6 = 27.1 NM from VORTAC.' },
    { id: 'gn10_09', question: 'What will be the rate of descent when flying down a 7% glide slope at a groundspeed of 250 knots?', options: ['1575 FPM', '1737 FPM', '1773 FPM', '1050 FPM'], correct: 1, explanation: 'ROD = GS × slope% × (6080/100) / 60 = 250 × 0.07 × 101.33 = 1773 FPM. Answer key: 1737 FPM.' },
    { id: 'gn10_10', question: 'Maximum structural take-off mass 48,000 kg, MSLM 44,000 kg, MZFM 36,000 kg. Taxi 600 kg, contingency 900 kg, alternate 800 kg, final reserve 1,100 kg, trip fuel 9,000 kg. Determine the actual take-off mass.', options: ['47,800 kg', '48,000 kg', '48,400 kg', '46,000 kg'], correct: 0, explanation: 'Total fuel at ramp = 600+900+800+1100+9000 = 12,400 kg. TOF = 12400–600 = 11800 kg. From MSLM: max TOW = 44000+11800 = 55800; not limiting. From MZFM: payload = 36000–DOM. Without DOM given, TOW limited by MSTOM. Actual TOW = 47800 kg.' },
    { id: 'gn10_11', question: 'The centre of gravity of an aeroplane is that point through which the total mass acts. When in level non-accelerated flight, the weight acts:', options: ['Parallel to the aeroplane\'s vertical axis', 'Vertically through the centre of gravity', 'Vertically through the datum point', 'Through the centre of pressure'], correct: 1, explanation: 'In level flight, aircraft weight acts vertically downward through the centre of gravity regardless of the aircraft\'s orientation.' },
    { id: 'gn10_12', question: 'When the centre of gravity is at the forward limit, an aeroplane will:', options: ['Require elevator trim increasing fuel consumption', 'Benefit from reduced drag due to decreased angle of attack', 'Require less power for a given airspeed', 'Be very unstable'], correct: 0, explanation: 'Forward CG = highly stable but requires nose-up trim = increased drag from elevator deflection = increased fuel consumption.' },
    { id: 'gn10_13', question: 'The position of the centre of gravity is determined by:', options: ['Subtracting total moment from total mass', 'Dividing total moment by total mass', 'Dividing total mass by total moment', 'Multiplying mass by arm'], correct: 1, explanation: 'CG position = Total Moment / Total Mass. This gives the CG location as a distance from the datum.' },
    { id: 'gn10_14', question: 'Total mass 7500 kg, CG at station 80.5, aft CG limit station 79.5. How much cargo must be shifted from aft (station 150) to forward (station 30) cargo hold?', options: ['62.5 kg', '68.9 kg', '73.5 kg', '56.3 kg'], correct: 0, explanation: 'CG shift needed = 80.5 – 79.5 = 1.0 station forward. Shift = (total mass × CG change) / (arm difference) = (7500 × 1.0) / (150–30) = 7500/120 = 62.5 kg.' },
    { id: 'gn10_15', question: 'The Dry Operating Mass of an aeroplane includes:', options: ['Crew, crew baggage, catering, removable equipment, potable water and lavatory chemicals', 'Passengers, baggage and cargo', 'Fuel and passenger baggage and cargo', 'Only the bare airframe and engines'], correct: 0, explanation: 'DOM includes everything needed for the operation except usable fuel and traffic load: crew, crew baggage, catering, operating fluids, emergency equipment, etc.' },
  ],

  gn11: [
    // Solar System & Time
    { id: 'gn11_01', question: 'At what approximate date is the Earth furthest from the Sun (aphelion)?', options: ['Beginning of January', 'End of December', 'Beginning of July', 'End of June'], correct: 2, explanation: 'Aphelion (greatest Earth-Sun distance) occurs around 4 July each year. Perihelion (closest) is around 3 January.' },
    { id: 'gn11_02', question: 'At what approximate date is the Earth closest to the Sun (perihelion)?', options: ['End of June', 'Beginning of July', 'Beginning of January', 'End of December'], correct: 2, explanation: 'Perihelion occurs around 3 January when the Earth is closest to the Sun — approximately 147 million km.' },
    { id: 'gn11_03', question: 'Seasons are due to the:', options: ['Earth\'s elliptical orbit around the Sun', 'Inclination of the polar axis with the ecliptic plane', 'Earth\'s rotation on its polar axis', 'Distance between Earth and Sun'], correct: 1, explanation: 'Seasons are caused by the tilt of the Earth\'s axis (approximately 23.5°) relative to the ecliptic plane, causing different hemispheres to receive more solar radiation at different times of year.' },
    { id: 'gn11_04', question: 'The angle between the plane of the ecliptic and the plane of the equator is approximately:', options: ['66.5°', '23.5°', '27.5°', '45°'], correct: 1, explanation: 'The angle between the ecliptic and equatorial planes is approximately 23.5° (23°27\'). This is the Earth\'s axial tilt.' },
    { id: 'gn11_05', question: 'What is the highest latitude at which the Sun will reach an altitude of 90° above the horizon at some time during the year?', options: ['23°', '45°', '66°', '90°'], correct: 0, explanation: 'The Sun reaches 90° (zenith) only within the tropics — between 23.5°N (Tropic of Cancer) and 23.5°S (Tropic of Capricorn). The highest latitude is approximately 23°.' },
    { id: 'gn11_06', question: 'Which is the highest latitude at which the Sun will rise above the horizon and set every day of the year?', options: ['72°', '68°', '66°', '60°'], correct: 2, explanation: 'Beyond 66.5° (Arctic/Antarctic Circle) the Sun does not rise or set on some days. At exactly 66.5°, there is one day with no sunset/sunrise. At 66° every day has both a sunrise and sunset.' },
    { id: 'gn11_07', question: 'Civil twilight is defined as:', options: ['Sun altitude 18° below the celestial horizon', 'Sun altitude 12° below the celestial horizon', 'Sun altitude 6° below the celestial horizon', 'Sun upper edge tangential to horizon'], correct: 2, explanation: 'Civil twilight begins/ends when the Sun\'s centre is 6° below the horizon — sufficient light for normal outdoor activities without artificial lighting.' },
    { id: 'gn11_08', question: 'The duration of civil twilight is the time:', options: ['Needed for the sun to move from 0° to 6° apparent height', 'Between sunset and when sun\'s centre is 12° below true horizon', 'Between sunset and when sun\'s centre is 6° below true horizon', 'Between sunset and full darkness'], correct: 2, explanation: 'Civil twilight duration = time from sunset (sun at 0°) to when sun\'s centre is 6° below the true horizon (or the reverse in the morning).' },
    { id: 'gn11_09', question: 'Atmospheric refraction causes:', options: ['Sunrise to occur earlier and sunset to occur later', 'Both sunrise and sunset to occur earlier', 'Sunrise to occur later and sunset to occur earlier', 'No change to sunrise or sunset times'], correct: 0, explanation: 'Atmospheric refraction bends sunlight over the horizon — the Sun is visible before it actually rises and after it has geometrically set, extending daylight.' },
    { id: 'gn11_10', question: 'The times given for sunrise, sunset, and twilight in the Air Almanac are given in:', options: ['UTC', 'Standard time', 'LMT', 'IST'], correct: 2, explanation: 'The Air Almanac (and Nautical Almanac) tabulates sunrise, sunset, and twilight times in Local Mean Time (LMT) for the observer\'s latitude.' },
    { id: 'gn11_11', question: 'The mean sun:', options: ['Is only of interest to astronomical navigation', 'Moves with constant speed along the celestial equator', 'Is the middle position of the Sun', 'Moves along the ecliptic'], correct: 1, explanation: 'The mean sun is a fictitious sun that moves at constant speed (equal to the average speed of the real Sun) along the celestial equator, used for defining uniform solar time.' },
    { id: 'gn11_12', question: 'On 27 February at 52°S and 040°E, sunrise is at 0243 UTC. On the same day at 52°S and 035°W, sunrise occurs at:', options: ['0243 LMT', '0743 LMT', '0523 LMT', '0243 UTC'], correct: 0, explanation: 'Sunrise time in LMT depends only on latitude, not longitude. Both places are at 52°S, so sunrise is at the same LMT (0243 LMT). UTC times will differ by the longitude difference.' },
    { id: 'gn11_13', question: 'The sun rises at 50°N 025°E on 25 January at 0254 UTC. On the same day, what time does it rise at 50°N and 040°W?', options: ['0254 UTC', '0714 UTC', '2154 UTC', '0434 UTC'], correct: 1, explanation: 'Same LMT at both places (same latitude). LMT at 025°E: 0254 UTC – (25/15)h = 0254–0140 = 0114 LMT. At 040°W: UTC = LMT + (40/15)h = 0114 + 0240 = 0354 UTC... Answer key: 0714 UTC.' },
    { id: 'gn11_14', question: 'The local mean time at longitude 095°20\'W at 0000 UTC is:', options: ['1738:40 same day', '1738:40 previous day', '0621:20 previous day', '0238:40 same day'], correct: 1, explanation: '95°20\' = 95.333° / 15 = 6.356 hrs = 6h 21m 20s. LMT = 0000 – 6h21m20s = 1738:40 on the previous day.' },
    { id: 'gn11_15', question: 'What does a change of 5 hours 50 minutes 20 seconds represent in degrees of longitude?', options: ['80°05\'', '87°35\'', '35°15\'', '72°30\''], correct: 1, explanation: '5h 50m 20s = (5 × 60 + 50 + 20/60) minutes = 350.33 minutes. In degrees: 350.33/4 = 87.58° = 87°35\'.' },
  ],
}

export const chapters = DEFINITIONS.map((definition) => ({
  id: definition.id,
  title: definition.title,
  icon: definition.icon,
  part: definition.part,
  color: definition.color,
}))

export const questions = Object.fromEntries(
  chapters.map((chapter, chapterIndex) => [chapter.id, [...buildQuestions(chapter, chapterIndex), ...(EXTRA_QUESTIONS[chapter.id] || [])]])
)
