export const chapters = [
  {
    id: 'rn01',
    title: 'Instrument Approach Basics',
    icon: '🛬',
    part: 'Instrument Navigation',
    color: '#0F766E',
  },
  {
    id: 'rn02',
    title: 'VOR and NDB',
    icon: '🧭',
    part: 'Instrument Navigation',
    color: '#0F766E',
  },
  {
    id: 'rn03',
    title: 'ILS and Marker Beacons',
    icon: '📡',
    part: 'Instrument Navigation',
    color: '#0F766E',
  },
  {
    id: 'rn04',
    title: 'DME and RNAV',
    icon: '📍',
    part: 'Instrument Navigation',
    color: '#0F766E',
  },
]

export const questions = {
  rn01: [
    {
      id: 'rn01_01',
      question: 'An instrument approach procedure is designed mainly to provide:',
      options: ['a safe descent path to landing', 'shorter taxi distance', 'more passenger comfort', 'higher fuel flow'],
      correct: 0,
      explanation: 'Instrument approach procedures guide an aircraft safely to a landing in poor visibility.',
    },
    {
      id: 'rn01_02',
      question: 'The primary reference for instrument navigation is:',
      options: ['the navigation aid and procedure', 'the cabin temperature', 'the passenger count', 'the paint scheme'],
      correct: 0,
      explanation: 'Instrument navigation depends on navigation aids and published procedures.',
    },
    {
      id: 'rn01_03',
      question: 'A missed approach is executed when:',
      options: ['the required visual or instrument requirements are not met', 'the aircraft is taxiing', 'the weather improves', 'the runway is clear'],
      correct: 0,
      explanation: 'A missed approach is required when the pilot cannot safely continue the approach.',
    },
    {
      id: 'rn01_04',
      question: 'A stable approach helps to:',
      options: ['reduce the chance of a go-around', 'increase fuel burn', 'reduce flaps', 'lower rpm'],
      correct: 0,
      explanation: 'A stable approach lowers the chance of a missed approach and unstable landing.',
    },
    {
      id: 'rn01_05',
      question: 'An approach briefing is important because it:',
      options: ['prepares the crew for the procedure', 'adds weight', 'reduces visibility', 'increases drag'],
      correct: 0,
      explanation: 'A briefing prepares the crew for the instrument procedure and expected actions.',
    },
    {
      id: 'rn01_06',
      question: 'Instrument procedures are published to:',
      options: ['standardize safe operations', 'increase ATC workload', 'reduce runway length', 'avoid weather'],
      correct: 0,
      explanation: 'Published procedures standardize safe instrument operations.',
    },
    {
      id: 'rn01_07',
      question: 'A pilot should monitor the approach path mainly to:',
      options: ['remain on the correct vertical and lateral path', 'reduce passenger noise', 'save fuel', 'change radio frequency'],
      correct: 0,
      explanation: 'Monitoring the path helps maintain correct alignment and descent profile.',
    },
    {
      id: 'rn01_08',
      question: 'An approach clearance is normally received from:',
      options: ['ATC', 'the cabin crew', 'ground handling', 'the weather office'],
      correct: 0,
      explanation: 'Approach clearance is provided by ATC for controlled airspace operations.',
    },
    {
      id: 'rn01_09',
      question: 'A missed approach point is a location where:',
      options: ['the pilot must decide whether to continue or go around', 'the aircraft turns off the runway', 'the aircraft enters the hold', 'the engine is shut down'],
      correct: 0,
      explanation: 'The missed approach point marks the decision point for continuing or going around.',
    },
    {
      id: 'rn01_10',
      question: 'The aim of instrument approach design is to:',
      options: ['provide a predictable procedure', 'reduce pilot training', 'increase runway slope', 'eliminate ATC'],
      correct: 0,
      explanation: 'Instrument approach design standardizes a predictable procedure for safe descent.',
    },
  ],
  rn02: [
    {
      id: 'rn02_01',
      question: 'A VOR provides bearing information relative to:',
      options: ['the VOR station', 'the runway threshold', 'the magnetic poles', 'the earth surface'],
      correct: 0,
      explanation: 'A VOR provides radial information from the station to the aircraft.',
    },
    {
      id: 'rn02_02',
      question: 'A VOR radial is measured from:',
      options: ['true north', 'magnetic north', 'runway heading', 'the aircraft tail'],
      correct: 0,
      explanation: 'VOR radials are referenced to magnetic north in the standard navigation frame.',
    },
    {
      id: 'rn02_03',
      question: 'An NDB provides guidance by means of:',
      options: ['radio bearings', 'visual lights', 'pressure altitude', 'GPS satellites'],
      correct: 0,
      explanation: 'NDB navigation relies on radio bearings from the ground station.',
    },
    {
      id: 'rn02_04',
      question: 'A VOR cone of ambiguity occurs because:',
      options: ['signals may be unreliable near the station', 'the aircraft is too slow', 'the weather is clear', 'the approach is visual'],
      correct: 0,
      explanation: 'VOR indications can become unreliable or ambiguous close to the station.',
    },
    {
      id: 'rn02_05',
      question: 'A VOR indicator is used mainly to determine:',
      options: ['bearing from the station', 'fuel quantity', 'aircraft weight', 'engine temperature'],
      correct: 0,
      explanation: 'The VOR indicator shows the aircraft’s bearing from the station.',
    },
    {
      id: 'rn02_06',
      question: 'The primary advantage of a VOR is that it provides:',
      options: ['line-of-position information', 'altitude information', 'oil pressure data', 'wind shear warnings'],
      correct: 0,
      explanation: 'A VOR provides line-of-position information through bearings from the beacon.',
    },
    {
      id: 'rn02_07',
      question: 'An ADF is normally tuned to:',
      options: ['an NDB', 'a VOR', 'an ILS localizer', 'a transponder'],
      correct: 0,
      explanation: 'ADF equipment is tuned to NDB stations for bearing information.',
    },
    {
      id: 'rn02_08',
      question: 'The bearing shown by ADF may be affected by:',
      options: ['station interference and aircraft attitude', 'fuel load only', 'runway width', 'crew size'],
      correct: 0,
      explanation: 'ADF bearings can be affected by station geometry and aircraft installation effects.',
    },
    {
      id: 'rn02_09',
      question: 'A VOR check is carried out to verify:',
      options: ['the VOR is operating correctly', 'the aircraft weight is legal', 'the cargo is balanced', 'the landing lights are on'],
      correct: 0,
      explanation: 'VOR checks verify that the navigation aid and receiver are functioning correctly.',
    },
    {
      id: 'rn02_10',
      question: 'A pilot should not rely on a VOR indication near the station because:',
      options: ['the cone of ambiguity can affect accuracy', 'the airspeed is too high', 'the weather is always good', 'the runway is closed'],
      correct: 0,
      explanation: 'VOR indications can become unreliable near the station because of the cone of ambiguity.',
    },
  ],
  rn03: [
    {
      id: 'rn03_01',
      question: 'The localizer provides guidance in:',
      options: ['azimuth', 'altitude', 'airspeed', 'temperature'],
      correct: 0,
      explanation: 'The localizer provides horizontal guidance toward the runway centerline.',
    },
    {
      id: 'rn03_02',
      question: 'The glide slope provides guidance in:',
      options: ['vertical descent', 'lateral drift', 'engine power', 'fuel quantity'],
      correct: 0,
      explanation: 'The glide slope provides vertical guidance for the descent path.',
    },
    {
      id: 'rn03_03',
      question: 'Marker beacons are used to indicate:',
      options: ['specific positions along the approach', 'windshear severity', 'engine temperatures', 'fuel types'],
      correct: 0,
      explanation: 'Marker beacons mark defined positions on the instrument approach.',
    },
    {
      id: 'rn03_04',
      question: 'The outer marker is used to indicate:',
      options: ['the beginning of the final approach segment', 'the touchdown point', 'the runway threshold', 'the missed approach point'],
      correct: 0,
      explanation: 'The outer marker identifies the beginning of the final approach segment.',
    },
    {
      id: 'rn03_05',
      question: 'The middle marker indicates:',
      options: ['a point near the decision altitude', 'engine start', 'holding pattern entry', 'takeoff roll'],
      correct: 0,
      explanation: 'The middle marker normally marks an area near the decision point for landing.',
    },
    {
      id: 'rn03_06',
      question: 'ILS guidance can be used when the aircraft is equipped with:',
      options: ['appropriate instruments', 'only a compass', 'only a stopwatch', 'only a radio'],
      correct: 0,
      explanation: 'ILS requires the aircraft to be equipped with suitable instruments for the approach.',
    },
    {
      id: 'rn03_07',
      question: 'A pilot should monitor the glide slope because it shows:',
      options: ['vertical guidance', 'runway length', 'fuel availability', 'weather radar data'],
      correct: 0,
      explanation: 'The glide slope provides vertical guidance to maintain the correct descent path.',
    },
    {
      id: 'rn03_08',
      question: 'The localizer is normally aligned with:',
      options: ['the runway centerline', 'the taxiway centerline', 'the terminal building', 'the approach light system'],
      correct: 0,
      explanation: 'The localizer is aligned with the runway centerline for the final approach.',
    },
    {
      id: 'rn03_09',
      question: 'A pilot may use a marker beacon to confirm:',
      options: ['distance from the runway', 'engine temperature', 'fuel quantity', 'altitude indication'],
      correct: 0,
      explanation: 'Marker beacons provide position information along the approach path.',
    },
    {
      id: 'rn03_10',
      question: 'An ILS procedure provides:',
      options: ['both lateral and vertical guidance', 'only weather information', 'only obstacle clearance', 'only fuel planning'],
      correct: 0,
      explanation: 'ILS provides both localizer and glide slope guidance.',
    },
  ],
  rn04: [
    {
      id: 'rn04_01',
      question: 'DME provides distance information from:',
      options: ['a navigation beacon', 'the runway threshold', 'ATC', 'the horizon'],
      correct: 0,
      explanation: 'DME measures slant range from the beacon to the aircraft.',
    },
    {
      id: 'rn04_02',
      question: 'RNAV is used mainly to:',
      options: ['navigate without relying solely on ground stations', 'reduce cabin pressure', 'increase approach speed', 'lower flap setting'],
      correct: 0,
      explanation: 'RNAV allows navigation using onboard systems and published waypoints.',
    },
    {
      id: 'rn04_03',
      question: 'A DME distance readout is usually expressed in:',
      options: ['NM', 'ft', 'kt', '°C'],
      correct: 0,
      explanation: 'DME distances are normally reported in nautical miles.',
    },
    {
      id: 'rn04_04',
      question: 'A pilot uses RNAV mainly to:',
      options: ['fly to defined waypoints', 'measure fuel temperature', 'increase cabin altitude', 'change runway lights'],
      correct: 0,
      explanation: 'RNAV guides the aircraft between defined waypoints.',
    },
    {
      id: 'rn04_05',
      question: 'DME can support approach navigation when:',
      options: ['the procedure uses DME', 'the weather is VFR', 'the runway is closed', 'the aircraft is on the ground'],
      correct: 0,
      explanation: 'Some procedures use DME as a navigation aid for position and distance.',
    },
    {
      id: 'rn04_06',
      question: 'RNAV system accuracy depends on:',
      options: ['the system and integrity of the source data', 'the airline logo', 'airport lights', 'passenger load'],
      correct: 0,
      explanation: 'RNAV performance depends on the system and the quality of the navigation source data.',
    },
    {
      id: 'rn04_07',
      question: 'A pilot should cross-check DME readings because they may be:',
      options: ['affected by slant range geometry', 'ignored by ATC', 'replaced by fuel data', 'limited to visual flight'],
      correct: 0,
      explanation: 'DME readings are slant-range values and should be interpreted with care.',
    },
    {
      id: 'rn04_08',
      question: 'A waypoint in RNAV is:',
      options: ['a defined position used for navigation', 'a runway threshold', 'a weather report', 'an engine gauge'],
      correct: 0,
      explanation: 'Waypoints are defined positions used in RNAV procedures.',
    },
    {
      id: 'rn04_09',
      question: 'A pilot should verify RNAV database currency because:',
      options: ['obsolete data can cause navigation errors', 'it changes the aircraft color', 'it reduces cabin pressure', 'it is not required'],
      correct: 0,
      explanation: 'Outdated navigation databases can lead to inaccurate procedures and guidance.',
    },
    {
      id: 'rn04_10',
      question: 'The use of DME on an approach often helps the pilot to:',
      options: ['determine distance from the station', 'change altitude', 'reduce engine rpm', 'enter the hold'],
      correct: 0,
      explanation: 'DME provides distance-from-station information during the approach.',
    },
  ],
}
